-- View that gives the original Excel headers back.
--   \copy (SELECT * FROM sales.v_pnl_excel) TO 'pnl.csv' WITH (FORMAT csv, HEADER true)
CREATE OR REPLACE VIEW sales.v_pnl_excel AS
SELECT
    cus_group                      AS "Cus_group",
    record_type                    AS "Type",
    division2                      AS "Division 2",
    prod_group                     AS "Prod_group",
    fiscal_year                    AS "Year",
    sold_to                        AS "sold To",
    forex_rate                     AS "Forex",
    sales_usd                      AS "Sales U$",
    op_profit_usd                  AS "Op Profit U$",
    customer                       AS "Customer",
    material_group                 AS "Material Group",
    nielsen_id                     AS "Nielsen ID",
    profit_center                  AS "Profit Center",
    sap_division                   AS "Division",
    distribution_channel           AS "Distribution Channel",
    period                         AS "Period",
    doc_currency                   AS "Currency",
    qty_gross                      AS "Quantity(Gross)",
    qty_return                     AS "Quantity(Return)",
    qty_net                        AS "Quantity(Net)",
    tot_s_rrp                      AS "*S.RRP",
    reference_price                AS "Reference Price",
    tot_dealer_discount            AS "*Delear Discount",
    s_base_margin                  AS "S.Base Margin",
    s_contract_margin              AS "S.Contract Margin",
    s_additional_margin            AS "S.Additional Margin",
    s_special_margin               AS "S.Special Margin",
    tot_s_gross_sales              AS "*S.Gross Sales",
    s_gross_sales_amt              AS "S.Gross Sales AMT",
    s_other_sales                  AS "S.Other Sales",
    s_oth_sales_tax_inc            AS "S.Oth Sales Tax Inc",
    s_internal_sales_amt           AS "S.Internal Sales Amt",
    tot_s_return_amt               AS "*S.Return Amt",
    s_return_amt                   AS "S.Return Amt",
    tot_ref_sales                  AS "*Ref. Sales",
    s_ifc                          AS "S.IFC",
    s_fob_sales_amt                AS "S.FOB Sales Amt",
    tot_sales_deduction            AS "*Sales Deduction",
    s_sales_allowance              AS "S.Sales Allowance",
    s_rebate                       AS "S.Rebate",
    s_cash_discount                AS "S.Cash Discount",
    s_price_protection             AS "S.Price Protection",
    s_co_op                        AS "S.CO-OP",
    s_sale_deduction_tax           AS "S.Sale Deduction TAX",
    tot_net_sales                  AS "*Net Sales",
    tot_cogs                       AS "*Cost of Goods Sold",
    tot_material_cost              AS "*Material Cost",
    sc_material_cost               AS "SC.Material Cost",
    sc_matl_cost_loss              AS "SC.Matl Cost-Loss",
    sc_cctr_matl_cost              AS "SC.Cctr Matl Cost",
    sc_cctr_matl_loss              AS "SC.Cctr Matl-Loss",
    sc_os_material_cost            AS "SC.OS Material Cost",
    sc_other_matl_cost             AS "SC.Other Matl Cost",
    tot_labor_cost                 AS "*Labor Cost",
    sc_labor_cost                  AS "SC.Labor Cost",
    sc_labor_salaries              AS "SC.Labor-Salaries",
    sc_labor_overtime              AS "SC.Labor-Overtime",
    sc_labor_cost_ps               AS "SC.Labor Cost(PS)",
    sc_labor_cost_rd               AS "SC.Labor Cost(RD)",
    tot_depreciation_exp           AS "*Depreciation Exp",
    sc_depre_exp                   AS "SC.Depre Exp",
    sc_depre_exp_on_bldg           AS "SC.Depre Exp on Bldg",
    sc_depre_exp_on_m_and_e        AS "SC.Depre Exp on M&E",
    tot_mold_exp                   AS "*Mold Exp",
    sc_depre_exp_on_mold           AS "SC.Depre Exp on Mold",
    sc_molds_cost                  AS "SC.Molds Cost",
    sc_cnc_molds_cost              AS "SC.CNC Molds Cost",
    tot_manufac_supp_cost          AS "*Manufac.supp.Cost",
    sc_mfg_supply_cost             AS "SC.Mfg Supply Cost",
    sc_mfg_repair_and_maint        AS "SC.Mfg Repair&Maint",
    sc_manufac_jig_cost            AS "SC.Manufac.JIG.Cost",
    sc_equip_repair_cost           AS "SC.Equip Repair Cost",
    sc_supplies_exp                AS "SC.Supplies Exp",
    tot_expense                    AS "*Expense",
    sc_amort_on_dev_cost           AS "SC.Amort on Dev Cost",
    sc_subcont_cost                AS "SC.Subcont. Cost",
    sc_part_time_svc_exp           AS "SC.Part Time SVC Exp",
    sc_royalty_3rd_party           AS "SC.Royalty-3rd Party",
    sc_royalty_hq                  AS "SC.Royalty-HQ",
    sc_utility                     AS "SC.Utility",
    sc_logistic_cost               AS "SC.Logistic Cost",
    sc_commission                  AS "SC.Commission",
    sc_it_cost                     AS "SC.IT Cost",
    sc_installation                AS "SC.Installation",
    sc_tax_and_dues                AS "SC.Tax&Dues",
    sc_telecom_exp                 AS "SC.Telecom Exp",
    sc_travel_exp                  AS "SC.Travel Exp",
    sc_rent_and_lease_exp          AS "SC.Rent&Lease Exp",
    sc_sample_exp                  AS "SC.Sample Exp",
    sc_packing_exp                 AS "SC.Packing Exp",
    sc_insurance_premium           AS "SC.Insurance Premium",
    sc_convention_exp              AS "SC.Convention Exp",
    sc_svc_exp                     AS "SC.SVC Exp",
    sc_other_exps                  AS "SC.Other Exps",
    sc_consumable_rd               AS "SC.Consumable(RD)",
    sc_ordinary_exp_matl           AS "SC.Ordinary Exp-Matl",
    sc_outsourcing_svc             AS "SC.Outsourcing SVC",
    sc_others_rd                   AS "SC.Othres(RD)",
    tot_other_cgs                  AS "*Other CGS",
    sc_other                       AS "SC.Other",
    sc_svc_warranty                AS "SC.SVC Warranty",
    sc_svc_agent_fee               AS "SC.SVC Agent Fee",
    tot_return_cgs                 AS "*Return CGS",
    sc_return_cgs                  AS "SC.Return CGS",
    tot_other_expense              AS "*Other Expense",
    tot_other_exp_detail           AS "*Other Exp.",
    sc_lcm                         AS "SC.LCM",
    sc_e_and_o                     AS "SC.E&O",
    sc_ramp_up_cost                AS "SC.Ramp-up Cost",
    sc_inv_loss_q                  AS "SC.INV Loss(Q)",
    sc_inv_loss_p                  AS "SC.INV Loss(P)",
    sc_subcontractor_adj           AS "SC.Subcontractor-Adj",
    sc_customs_refund              AS "SC.Customs Refund",
    sc_matl_price_settle           AS "SC.Matl Price Settle",
    sc_vat_china                   AS "SC.VAT (China)",
    sc_cgs_others                  AS "SC.CGS Others",
    tot_logistic_cost_c_type       AS "*Logistic Cost(C Type)",
    sc_transport_inland            AS "SC.Transport-Inland",
    sc_transport_marine            AS "SC.Transport-Marine",
    sc_transport_air               AS "SC.Transport-Air",
    sc_transport_other             AS "SC.Transport-Other",
    sc_insurance_logis             AS "SC.Insurance (Logis)",
    tot_internal_cgs               AS "*Internal CGS",
    sc_internal_cgs                AS "SC.Internal CGS",
    tot_ref_cogs                   AS "*Ref. CoGS",
    sc_stat_customs_fee            AS "SC.Stat.Customs Fee",
    sc_stat_incidental             AS "SC.Stat Incidental",
    sc_stat_sub_line_exp           AS "SC.Stat.Sub-Line Exp",
    tot_gross_margin               AS "*Gross Margin",
    tot_operating_expense          AS "*Operating Expense",
    tot_sales_expense              AS "*Sales Expense",
    tot_labor_cost_s               AS "*Labor Cost(S)",
    sa_labor_cost                  AS "SA.Labor Cost",
    sa_labor_salaries              AS "SA.Labor-Salaries",
    tot_svc_expense                AS "*SVC Expense",
    sa_svc_warranty                AS "SA.SVC Warranty",
    sa_svc_qual_support            AS "SA.SVC Qual Support",
    sa_svc_agency_fee              AS "SA.SVC Agency Fee",
    sa_svc_call_center             AS "SA.SVC Call Center",
    sa_svc_claim                   AS "SA.SVC Claim",
    sa_svc_freight                 AS "SA.SVC Freight",
    sa_svc_circulation             AS "SA.SVC Circulation",
    sa_svc_op_support              AS "SA.SVC Op Support",
    sa_svc_other_exp               AS "SA.SVC Other Exp",
    tot_logistics_cost             AS "*Logistics Cost",
    sa_transport_inland            AS "SA.Transport-Inland",
    sa_transport_marine            AS "SA.Transport-Marine",
    sa_transport_air               AS "SA.Transport-Air",
    sa_transport_other             AS "SA.Transport-Other",
    sa_warehouse_fee               AS "SA.Warehouse Fee",
    sa_insurance_logis             AS "SA.Insurance (Logis)",
    sa_comm                        AS "SA.Comm",
    tot_marketing_expense          AS "*Marketing Expense",
    sa_advertising                 AS "SA.Advertising",
    sa_co_op                       AS "SA.CO-OP",
    sa_promotion                   AS "SA.Promotion",
    sa_market_research             AS "SA.Market Research",
    sa_sales_commission            AS "SA.Sales Commission",
    sa_comm_and_svcchgc_card       AS "SA.Comm&SvcChgC.Card",
    sa_hq_sales_comm               AS "SA.HQ Sales Comm",
    sa_corp_promotion              AS "SA.Corp. Promotion",
    tot_royalty                    AS "*Royalty",
    sa_royalty_3rd_party           AS "SA.Royalty-3rd Party",
    sa_royalty_hq                  AS "SA.Royalty-HQ",
    sa_royalty_lump_sum            AS "SA.Royalty-Lump Sum",
    tot_paid_commission            AS "*Paid Commission",
    sa_comm_consult                AS "SA.Comm-Consult",
    sa_comm_litigation             AS "SA.Comm-Litigation",
    sa_comm_audit                  AS "SA.Comm-Audit",
    sa_comm_d_o                    AS "SA.Comm-D/O",
    sa_paid_comm                   AS "SA.Paid Comm",
    tot_other_expense_s            AS "*Other Expense(S)",
    sa_depreciation                AS "SA.Depreciation",
    sa_insurance_premium           AS "SA.Insurance Premium",
    sa_sample                      AS "SA.Sample",
    sa_it_exp                      AS "SA.IT Exp",
    sa_lease_and_rent              AS "SA.Lease&Rent",
    sa_bad_debt_exp                AS "SA.Bad Debt Exp",
    sa_travel_exp                  AS "SA.Travel Exp",
    sa_telecom_exp                 AS "SA.Telecom Exp",
    sa_event_exp                   AS "SA.Event Exp",
    sa_survey_exp                  AS "SA.Survey Exp",
    sa_social_exp                  AS "SA.Social Exp",
    sa_convention_exp              AS "SA.Convention Exp",
    sa_copyright                   AS "SA.Copyright",
    sa_weee                        AS "SA.WEEE",
    sa_familynet                   AS "SA.Familynet",
    sa_other_exp                   AS "SA.Other Exp",
    tot_r_and_d_expense            AS "*R&D Expense",
    tot_internal_expense           AS "*Internal Expense",
    rd_ordinary_exp_matl           AS "RD.Ordinary Exp-Matl",
    rd_labor                       AS "RD Labor",
    rd_depreciation                AS "RD.Depreciation",
    rd_consumable                  AS "RD.Consumable",
    rd_others                      AS "RD.Others",
    rd_er                          AS "RD.ER",
    rd_mask                        AS "RD.Mask",
    tot_external_expense           AS "*External Expense",
    rd_royalty                     AS "RD.Royalty",
    rd_outsourcing_svc             AS "RD.Outsourcing SVC",
    tot_g_and_a_expense            AS "*G&A Expense",
    tot_labor_cost_sa              AS "*Labor Cost(SA)",
    ga_labor_cost                  AS "GA.Labor Cost",
    ga_labor_salaries              AS "GA.Labor-Salaries",
    tot_paid_commission_sa         AS "*Paid Commission(SA)",
    ga_comm_consult                AS "GA.Comm-Consult",
    ga_comm_litigation             AS "GA.Comm-Litigation",
    ga_comm_audit                  AS "GA.Comm-Audit",
    ga_comm_d_o                    AS "GA.Comm-D/O",
    ga_comm                        AS "GA.Comm",
    tot_expense_s                  AS "*Expense(S)",
    ga_depreciation                AS "GA.Depreciation",
    ga_it_exp                      AS "GA.IT Exp",
    ga_rent_exp                    AS "GA.Rent Exp",
    ga_telecom_exp                 AS "GA.Telecom Exp",
    ga_repairs_and_maint_exp       AS "GA.Repairs&Maint Exp",
    ga_travel_exp                  AS "GA.Travel Exp",
    ga_insurance_premium           AS "GA.Insurance Premium",
    ga_convention_exp              AS "GA.Convention Exp",
    ga_other                       AS "GA.Other",
    tot_operating_profit           AS "*Operating Profit",
    tot_non_op_income_and_expense  AS "*Non-Op. Incom. & Ex",
    tot_non_op_income              AS "*Non-Op. Income",
    op_commission_3rd              AS "OP.Commission 3rd",
    op_service_claim               AS "OP.Service Claim",
    op_rental_income               AS "OP.Rental Income",
    op_extra_gain                  AS "OP.Extra Gain",
    op_others                      AS "OP.Others",
    tot_non_op_expense             AS "*Non-Op. Expense",
    oe_loss_on_a_r_sale            AS "OE.Loss on A/R Sale",
    oe_extra_loss                  AS "OE.Extra Loss",
    oe_others                      AS "OE.Others",
    tot_gain_loss_on_equity        AS "*Gain/Loss on Equity",
    tot_gain_on_equity             AS "*Gain on Equity",
    eg_gain_on_equity              AS "EG.Gain on Equity",
    tot_loss_on_equity             AS "*Loss on Equity",
    el_loss_on_equity              AS "EL.Loss on Equity",
    tot_financial_income_and_expense AS "*Financial  Incom. & Exp.",
    tot_finance_profit             AS "*Finance Profit",
    fp_gain_on_fx                  AS "FP.Gain on FX",
    fp_interest_income             AS "FP.Interest Income",
    fp_fin_profit_oths             AS "FP.Fin Profit-Oths",
    tot_finance_loss               AS "*Finance Loss",
    fe_fo_ex_loss                  AS "FE.Fo.Ex.Loss",
    fe_interest_exp_ext            AS "FE.Interest Exp-Ext",
    fe_interest_exp_int            AS "FE.Interest Exp-Int",
    fe_financial_exp_oth           AS "FE.Financial Exp-Oth",
    tot_profit_before_tax          AS "*Profit Before Tax",
    tot_corporate_tax              AS "*Corporate Tax",
    corp_tax                       AS "Corp. Tax",
    tot_net_income                 AS "*Net Income"
FROM sales.pnl_fact;
