-- One-file setup for sales_2526: database -> table -> CSV load -> checks.
-- Open in MySQL Workbench and hit Execute All. Nothing else is needed.
--
-- Before running, check two things:
--   1) the file path below. Use forward slashes; a backslash is an escape char.
--   2) Workbench connection > Advanced > Others must have OPT_LOCAL_INFILE=1,
--      otherwise the load fails with error 3948.
--
-- For a tab-separated file, change the FIELDS line to:
--     FIELDS TERMINATED BY '\t' ESCAPED BY ''
--
-- Excel saves plain "CSV (Comma delimited)" in the Windows ANSI code page, not
-- UTF-8. Loading that as utf8mb4 fails with error 1300 - either set
-- CHARACTER SET euckr below, or re-save the file as "CSV UTF-8" from Excel.

SET GLOBAL local_infile = 1;

-- == 1. Cleanup functions ========
--    "1,268.93" -> 1268.93,  "" / "#N/A" -> NULL,  "(12.50)" -> -12.50

CREATE DATABASE IF NOT EXISTS sales_2526 DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;
USE sales_2526;

-- Excel-style number string -> decimal  ("1,268.93", "(1,234)", "", "-", "#N/A")
-- Anything that is not a plain number becomes NULL rather than raising, so a
-- misaligned file cannot abort the load halfway through. The reconciliation
-- queries at the end are what tell you the file was misaligned.
DROP FUNCTION IF EXISTS to_num;
DROP FUNCTION IF EXISTS to_txt;
DELIMITER $$

CREATE FUNCTION to_num(v text) RETURNS decimal(18,4)
DETERMINISTIC
BEGIN
    DECLARE t varchar(255);
    SET t = LEFT(REPLACE(REPLACE(REPLACE(TRIM(COALESCE(v, '')), ',', ''),
                                 '$', ''), ' ', ''), 255);
    IF t = '' OR t IN ('-', '#N/A', 'N/A', '#DIV/0!', '#VALUE!') THEN
        RETURN NULL;
    END IF;
    IF t LIKE '(%)' THEN                       -- accounting negative (12.50) -> -12.50
        SET t = CONCAT('-', SUBSTRING(t, 2, CHAR_LENGTH(t) - 2));
    END IF;
    IF CHAR_LENGTH(t) > 30 OR t NOT REGEXP '^-?[0-9]*\.?[0-9]+$' THEN
        RETURN NULL;
    END IF;
    RETURN CAST(t AS decimal(18,4));
END$$

-- Dimension text: trim, and turn blank / #N/A into NULL
CREATE FUNCTION to_txt(v text) RETURNS varchar(260)
DETERMINISTIC
BEGIN
    DECLARE t varchar(260);
    SET t = LEFT(TRIM(COALESCE(v, '')), 260);
    IF t = '' OR t = '#N/A' THEN
        RETURN NULL;
    END IF;
    RETURN t;
END$$

DELIMITER ;

-- == 2. Table ========
--    Column order matches the sheet 1:1; each comment is the original header.

DROP TABLE IF EXISTS pnl_fact;
CREATE TABLE pnl_fact (
    pnl_id           bigint NOT NULL AUTO_INCREMENT PRIMARY KEY,

    -- == Header / aggregation keys (left block of the sheet) ========
    cus_group                         varchar(20)            COMMENT 'Cus_group',
    record_type                       varchar(10)            COMMENT 'Type',
    division2                         varchar(20)            COMMENT 'Division 2',
    prod_group                        varchar(20)            COMMENT 'Prod_group',
    fiscal_year                       smallint NOT NULL      COMMENT 'Year',
    sold_to                           varchar(20)            COMMENT 'sold To',
    forex_rate                        decimal(18,9)          COMMENT 'Forex',
    sales_usd                         decimal(18,2)          COMMENT 'Sales U$',
    op_profit_usd                     decimal(18,2)          COMMENT 'Op Profit U$',

    -- == SAP dimensions ========
    customer                          varchar(20)            COMMENT 'Customer',
    material_group                    varchar(20)            COMMENT 'Material Group',
    nielsen_id                        varchar(20)            COMMENT 'Nielsen ID',
    profit_center                     varchar(20)            COMMENT 'Profit Center',
    sap_division                      varchar(10)            COMMENT 'Division',
    distribution_channel              varchar(10)            COMMENT 'Distribution Channel',
    period                            varchar(10) NOT NULL   COMMENT 'Period',
    doc_currency                      varchar(10)            COMMENT 'Currency',

    -- == Quantity ========
    qty_gross                         decimal(18,3)          COMMENT 'Quantity(Gross)',
    qty_return                        decimal(18,3)          COMMENT 'Quantity(Return)',
    qty_net                           decimal(18,3)          COMMENT 'Quantity(Net)',

    -- == Sales ========
    tot_s_rrp                         decimal(18,2)          COMMENT '*S.RRP',
    reference_price                   decimal(18,2)          COMMENT 'Reference Price',
    tot_dealer_discount               decimal(18,2)          COMMENT '*Delear Discount',
    s_base_margin                     decimal(18,2)          COMMENT 'S.Base Margin',
    s_contract_margin                 decimal(18,2)          COMMENT 'S.Contract Margin',
    s_additional_margin               decimal(18,2)          COMMENT 'S.Additional Margin',
    s_special_margin                  decimal(18,2)          COMMENT 'S.Special Margin',
    tot_s_gross_sales                 decimal(18,2)          COMMENT '*S.Gross Sales',
    s_gross_sales_amt                 decimal(18,2)          COMMENT 'S.Gross Sales AMT',
    s_other_sales                     decimal(18,2)          COMMENT 'S.Other Sales',
    s_oth_sales_tax_inc               decimal(18,2)          COMMENT 'S.Oth Sales Tax Inc',
    s_internal_sales_amt              decimal(18,2)          COMMENT 'S.Internal Sales Amt',
    tot_s_return_amt                  decimal(18,2)          COMMENT '*S.Return Amt',
    s_return_amt                      decimal(18,2)          COMMENT 'S.Return Amt',
    tot_ref_sales                     decimal(18,2)          COMMENT '*Ref. Sales',
    s_ifc                             decimal(18,2)          COMMENT 'S.IFC',
    s_fob_sales_amt                   decimal(18,2)          COMMENT 'S.FOB Sales Amt',
    tot_sales_deduction               decimal(18,2)          COMMENT '*Sales Deduction',
    s_sales_allowance                 decimal(18,2)          COMMENT 'S.Sales Allowance',
    s_rebate                          decimal(18,2)          COMMENT 'S.Rebate',
    s_cash_discount                   decimal(18,2)          COMMENT 'S.Cash Discount',
    s_price_protection                decimal(18,2)          COMMENT 'S.Price Protection',
    s_co_op                           decimal(18,2)          COMMENT 'S.CO-OP',
    s_sale_deduction_tax              decimal(18,2)          COMMENT 'S.Sale Deduction TAX',
    tot_net_sales                     decimal(18,2)          COMMENT '*Net Sales',

    -- == Cost of goods sold ========
    tot_cogs                          decimal(18,2)          COMMENT '*Cost of Goods Sold',
    tot_material_cost                 decimal(18,2)          COMMENT '*Material Cost',
    sc_material_cost                  decimal(18,2)          COMMENT 'SC.Material Cost',
    sc_matl_cost_loss                 decimal(18,2)          COMMENT 'SC.Matl Cost-Loss',
    sc_cctr_matl_cost                 decimal(18,2)          COMMENT 'SC.Cctr Matl Cost',
    sc_cctr_matl_loss                 decimal(18,2)          COMMENT 'SC.Cctr Matl-Loss',
    sc_os_material_cost               decimal(18,2)          COMMENT 'SC.OS Material Cost',
    sc_other_matl_cost                decimal(18,2)          COMMENT 'SC.Other Matl Cost',
    tot_labor_cost                    decimal(18,2)          COMMENT '*Labor Cost',
    sc_labor_cost                     decimal(18,2)          COMMENT 'SC.Labor Cost',
    sc_labor_salaries                 decimal(18,2)          COMMENT 'SC.Labor-Salaries',
    sc_labor_overtime                 decimal(18,2)          COMMENT 'SC.Labor-Overtime',
    sc_labor_cost_ps                  decimal(18,2)          COMMENT 'SC.Labor Cost(PS)',
    sc_labor_cost_rd                  decimal(18,2)          COMMENT 'SC.Labor Cost(RD)',
    tot_depreciation_exp              decimal(18,2)          COMMENT '*Depreciation Exp',
    sc_depre_exp                      decimal(18,2)          COMMENT 'SC.Depre Exp',
    sc_depre_exp_on_bldg              decimal(18,2)          COMMENT 'SC.Depre Exp on Bldg',
    sc_depre_exp_on_m_and_e           decimal(18,2)          COMMENT 'SC.Depre Exp on M&E',
    tot_mold_exp                      decimal(18,2)          COMMENT '*Mold Exp',
    sc_depre_exp_on_mold              decimal(18,2)          COMMENT 'SC.Depre Exp on Mold',
    sc_molds_cost                     decimal(18,2)          COMMENT 'SC.Molds Cost',
    sc_cnc_molds_cost                 decimal(18,2)          COMMENT 'SC.CNC Molds Cost',
    tot_manufac_supp_cost             decimal(18,2)          COMMENT '*Manufac.supp.Cost',
    sc_mfg_supply_cost                decimal(18,2)          COMMENT 'SC.Mfg Supply Cost',
    sc_mfg_repair_and_maint           decimal(18,2)          COMMENT 'SC.Mfg Repair&Maint',
    sc_manufac_jig_cost               decimal(18,2)          COMMENT 'SC.Manufac.JIG.Cost',
    sc_equip_repair_cost              decimal(18,2)          COMMENT 'SC.Equip Repair Cost',
    sc_supplies_exp                   decimal(18,2)          COMMENT 'SC.Supplies Exp',
    tot_expense                       decimal(18,2)          COMMENT '*Expense',
    sc_amort_on_dev_cost              decimal(18,2)          COMMENT 'SC.Amort on Dev Cost',
    sc_subcont_cost                   decimal(18,2)          COMMENT 'SC.Subcont. Cost',
    sc_part_time_svc_exp              decimal(18,2)          COMMENT 'SC.Part Time SVC Exp',
    sc_royalty_3rd_party              decimal(18,2)          COMMENT 'SC.Royalty-3rd Party',
    sc_royalty_hq                     decimal(18,2)          COMMENT 'SC.Royalty-HQ',
    sc_utility                        decimal(18,2)          COMMENT 'SC.Utility',
    sc_logistic_cost                  decimal(18,2)          COMMENT 'SC.Logistic Cost',
    sc_commission                     decimal(18,2)          COMMENT 'SC.Commission',
    sc_it_cost                        decimal(18,2)          COMMENT 'SC.IT Cost',
    sc_installation                   decimal(18,2)          COMMENT 'SC.Installation',
    sc_tax_and_dues                   decimal(18,2)          COMMENT 'SC.Tax&Dues',
    sc_telecom_exp                    decimal(18,2)          COMMENT 'SC.Telecom Exp',
    sc_travel_exp                     decimal(18,2)          COMMENT 'SC.Travel Exp',
    sc_rent_and_lease_exp             decimal(18,2)          COMMENT 'SC.Rent&Lease Exp',
    sc_sample_exp                     decimal(18,2)          COMMENT 'SC.Sample Exp',
    sc_packing_exp                    decimal(18,2)          COMMENT 'SC.Packing Exp',
    sc_insurance_premium              decimal(18,2)          COMMENT 'SC.Insurance Premium',
    sc_convention_exp                 decimal(18,2)          COMMENT 'SC.Convention Exp',
    sc_svc_exp                        decimal(18,2)          COMMENT 'SC.SVC Exp',
    sc_other_exps                     decimal(18,2)          COMMENT 'SC.Other Exps',
    sc_consumable_rd                  decimal(18,2)          COMMENT 'SC.Consumable(RD)',
    sc_ordinary_exp_matl              decimal(18,2)          COMMENT 'SC.Ordinary Exp-Matl',
    sc_outsourcing_svc                decimal(18,2)          COMMENT 'SC.Outsourcing SVC',
    sc_others_rd                      decimal(18,2)          COMMENT 'SC.Othres(RD)',
    tot_other_cgs                     decimal(18,2)          COMMENT '*Other CGS',
    sc_other                          decimal(18,2)          COMMENT 'SC.Other',
    sc_svc_warranty                   decimal(18,2)          COMMENT 'SC.SVC Warranty',
    sc_svc_agent_fee                  decimal(18,2)          COMMENT 'SC.SVC Agent Fee',
    tot_return_cgs                    decimal(18,2)          COMMENT '*Return CGS',
    sc_return_cgs                     decimal(18,2)          COMMENT 'SC.Return CGS',
    tot_other_expense                 decimal(18,2)          COMMENT '*Other Expense',
    tot_other_exp_detail              decimal(18,2)          COMMENT '*Other Exp.',
    sc_lcm                            decimal(18,2)          COMMENT 'SC.LCM',
    sc_e_and_o                        decimal(18,2)          COMMENT 'SC.E&O',
    sc_ramp_up_cost                   decimal(18,2)          COMMENT 'SC.Ramp-up Cost',
    sc_inv_loss_q                     decimal(18,2)          COMMENT 'SC.INV Loss(Q)',
    sc_inv_loss_p                     decimal(18,2)          COMMENT 'SC.INV Loss(P)',
    sc_subcontractor_adj              decimal(18,2)          COMMENT 'SC.Subcontractor-Adj',
    sc_customs_refund                 decimal(18,2)          COMMENT 'SC.Customs Refund',
    sc_matl_price_settle              decimal(18,2)          COMMENT 'SC.Matl Price Settle',
    sc_vat_china                      decimal(18,2)          COMMENT 'SC.VAT (China)',
    sc_cgs_others                     decimal(18,2)          COMMENT 'SC.CGS Others',
    tot_logistic_cost_c_type          decimal(18,2)          COMMENT '*Logistic Cost(C Type)',
    sc_transport_inland               decimal(18,2)          COMMENT 'SC.Transport-Inland',
    sc_transport_marine               decimal(18,2)          COMMENT 'SC.Transport-Marine',
    sc_transport_air                  decimal(18,2)          COMMENT 'SC.Transport-Air',
    sc_transport_other                decimal(18,2)          COMMENT 'SC.Transport-Other',
    sc_insurance_logis                decimal(18,2)          COMMENT 'SC.Insurance (Logis)',
    tot_internal_cgs                  decimal(18,2)          COMMENT '*Internal CGS',
    sc_internal_cgs                   decimal(18,2)          COMMENT 'SC.Internal CGS',
    tot_ref_cogs                      decimal(18,2)          COMMENT '*Ref. CoGS',
    sc_stat_customs_fee               decimal(18,2)          COMMENT 'SC.Stat.Customs Fee',
    sc_stat_incidental                decimal(18,2)          COMMENT 'SC.Stat Incidental',
    sc_stat_sub_line_exp              decimal(18,2)          COMMENT 'SC.Stat.Sub-Line Exp',

    -- == Gross margin / operating expense ========
    tot_gross_margin                  decimal(18,2)          COMMENT '*Gross Margin',
    tot_operating_expense             decimal(18,2)          COMMENT '*Operating Expense',
    tot_sales_expense                 decimal(18,2)          COMMENT '*Sales Expense',
    tot_labor_cost_s                  decimal(18,2)          COMMENT '*Labor Cost(S)',
    sa_labor_cost                     decimal(18,2)          COMMENT 'SA.Labor Cost',
    sa_labor_salaries                 decimal(18,2)          COMMENT 'SA.Labor-Salaries',
    tot_svc_expense                   decimal(18,2)          COMMENT '*SVC Expense',
    sa_svc_warranty                   decimal(18,2)          COMMENT 'SA.SVC Warranty',
    sa_svc_qual_support               decimal(18,2)          COMMENT 'SA.SVC Qual Support',
    sa_svc_agency_fee                 decimal(18,2)          COMMENT 'SA.SVC Agency Fee',
    sa_svc_call_center                decimal(18,2)          COMMENT 'SA.SVC Call Center',
    sa_svc_claim                      decimal(18,2)          COMMENT 'SA.SVC Claim',
    sa_svc_freight                    decimal(18,2)          COMMENT 'SA.SVC Freight',
    sa_svc_circulation                decimal(18,2)          COMMENT 'SA.SVC Circulation',
    sa_svc_op_support                 decimal(18,2)          COMMENT 'SA.SVC Op Support',
    sa_svc_other_exp                  decimal(18,2)          COMMENT 'SA.SVC Other Exp',
    tot_logistics_cost                decimal(18,2)          COMMENT '*Logistics Cost',
    sa_transport_inland               decimal(18,2)          COMMENT 'SA.Transport-Inland',
    sa_transport_marine               decimal(18,2)          COMMENT 'SA.Transport-Marine',
    sa_transport_air                  decimal(18,2)          COMMENT 'SA.Transport-Air',
    sa_transport_other                decimal(18,2)          COMMENT 'SA.Transport-Other',
    sa_warehouse_fee                  decimal(18,2)          COMMENT 'SA.Warehouse Fee',
    sa_insurance_logis                decimal(18,2)          COMMENT 'SA.Insurance (Logis)',
    sa_comm                           decimal(18,2)          COMMENT 'SA.Comm',
    tot_marketing_expense             decimal(18,2)          COMMENT '*Marketing Expense',
    sa_advertising                    decimal(18,2)          COMMENT 'SA.Advertising',
    sa_co_op                          decimal(18,2)          COMMENT 'SA.CO-OP',
    sa_promotion                      decimal(18,2)          COMMENT 'SA.Promotion',
    sa_market_research                decimal(18,2)          COMMENT 'SA.Market Research',
    sa_sales_commission               decimal(18,2)          COMMENT 'SA.Sales Commission',
    sa_comm_and_svcchgc_card          decimal(18,2)          COMMENT 'SA.Comm&SvcChgC.Card',
    sa_hq_sales_comm                  decimal(18,2)          COMMENT 'SA.HQ Sales Comm',
    sa_corp_promotion                 decimal(18,2)          COMMENT 'SA.Corp. Promotion',
    tot_royalty                       decimal(18,2)          COMMENT '*Royalty',
    sa_royalty_3rd_party              decimal(18,2)          COMMENT 'SA.Royalty-3rd Party',
    sa_royalty_hq                     decimal(18,2)          COMMENT 'SA.Royalty-HQ',
    sa_royalty_lump_sum               decimal(18,2)          COMMENT 'SA.Royalty-Lump Sum',
    tot_paid_commission               decimal(18,2)          COMMENT '*Paid Commission',
    sa_comm_consult                   decimal(18,2)          COMMENT 'SA.Comm-Consult',
    sa_comm_litigation                decimal(18,2)          COMMENT 'SA.Comm-Litigation',
    sa_comm_audit                     decimal(18,2)          COMMENT 'SA.Comm-Audit',
    sa_comm_d_o                       decimal(18,2)          COMMENT 'SA.Comm-D/O',
    sa_paid_comm                      decimal(18,2)          COMMENT 'SA.Paid Comm',
    tot_other_expense_s               decimal(18,2)          COMMENT '*Other Expense(S)',
    sa_depreciation                   decimal(18,2)          COMMENT 'SA.Depreciation',
    sa_insurance_premium              decimal(18,2)          COMMENT 'SA.Insurance Premium',
    sa_sample                         decimal(18,2)          COMMENT 'SA.Sample',
    sa_it_exp                         decimal(18,2)          COMMENT 'SA.IT Exp',
    sa_lease_and_rent                 decimal(18,2)          COMMENT 'SA.Lease&Rent',
    sa_bad_debt_exp                   decimal(18,2)          COMMENT 'SA.Bad Debt Exp',
    sa_travel_exp                     decimal(18,2)          COMMENT 'SA.Travel Exp',
    sa_telecom_exp                    decimal(18,2)          COMMENT 'SA.Telecom Exp',
    sa_event_exp                      decimal(18,2)          COMMENT 'SA.Event Exp',
    sa_survey_exp                     decimal(18,2)          COMMENT 'SA.Survey Exp',
    sa_social_exp                     decimal(18,2)          COMMENT 'SA.Social Exp',
    sa_convention_exp                 decimal(18,2)          COMMENT 'SA.Convention Exp',
    sa_copyright                      decimal(18,2)          COMMENT 'SA.Copyright',
    sa_weee                           decimal(18,2)          COMMENT 'SA.WEEE',
    sa_familynet                      decimal(18,2)          COMMENT 'SA.Familynet',
    sa_other_exp                      decimal(18,2)          COMMENT 'SA.Other Exp',

    -- == R&D expense ========
    tot_r_and_d_expense               decimal(18,2)          COMMENT '*R&D Expense',
    tot_internal_expense              decimal(18,2)          COMMENT '*Internal Expense',
    rd_ordinary_exp_matl              decimal(18,2)          COMMENT 'RD.Ordinary Exp-Matl',
    rd_labor                          decimal(18,2)          COMMENT 'RD Labor',
    rd_depreciation                   decimal(18,2)          COMMENT 'RD.Depreciation',
    rd_consumable                     decimal(18,2)          COMMENT 'RD.Consumable',
    rd_others                         decimal(18,2)          COMMENT 'RD.Others',
    rd_er                             decimal(18,2)          COMMENT 'RD.ER',
    rd_mask                           decimal(18,2)          COMMENT 'RD.Mask',
    tot_external_expense              decimal(18,2)          COMMENT '*External Expense',
    rd_royalty                        decimal(18,2)          COMMENT 'RD.Royalty',
    rd_outsourcing_svc                decimal(18,2)          COMMENT 'RD.Outsourcing SVC',

    -- == G&A expense ========
    tot_g_and_a_expense               decimal(18,2)          COMMENT '*G&A Expense',
    tot_labor_cost_sa                 decimal(18,2)          COMMENT '*Labor Cost(SA)',
    ga_labor_cost                     decimal(18,2)          COMMENT 'GA.Labor Cost',
    ga_labor_salaries                 decimal(18,2)          COMMENT 'GA.Labor-Salaries',
    tot_paid_commission_sa            decimal(18,2)          COMMENT '*Paid Commission(SA)',
    ga_comm_consult                   decimal(18,2)          COMMENT 'GA.Comm-Consult',
    ga_comm_litigation                decimal(18,2)          COMMENT 'GA.Comm-Litigation',
    ga_comm_audit                     decimal(18,2)          COMMENT 'GA.Comm-Audit',
    ga_comm_d_o                       decimal(18,2)          COMMENT 'GA.Comm-D/O',
    ga_comm                           decimal(18,2)          COMMENT 'GA.Comm',
    tot_expense_s                     decimal(18,2)          COMMENT '*Expense(S)',
    ga_depreciation                   decimal(18,2)          COMMENT 'GA.Depreciation',
    ga_it_exp                         decimal(18,2)          COMMENT 'GA.IT Exp',
    ga_rent_exp                       decimal(18,2)          COMMENT 'GA.Rent Exp',
    ga_telecom_exp                    decimal(18,2)          COMMENT 'GA.Telecom Exp',
    ga_repairs_and_maint_exp          decimal(18,2)          COMMENT 'GA.Repairs&Maint Exp',
    ga_travel_exp                     decimal(18,2)          COMMENT 'GA.Travel Exp',
    ga_insurance_premium              decimal(18,2)          COMMENT 'GA.Insurance Premium',
    ga_convention_exp                 decimal(18,2)          COMMENT 'GA.Convention Exp',
    ga_other                          decimal(18,2)          COMMENT 'GA.Other',

    -- == Operating profit and below ========
    tot_operating_profit              decimal(18,2)          COMMENT '*Operating Profit',
    tot_non_op_income_and_expense     decimal(18,2)          COMMENT '*Non-Op. Incom. & Ex',
    tot_non_op_income                 decimal(18,2)          COMMENT '*Non-Op. Income',
    op_commission_3rd                 decimal(18,2)          COMMENT 'OP.Commission 3rd',
    op_service_claim                  decimal(18,2)          COMMENT 'OP.Service Claim',
    op_rental_income                  decimal(18,2)          COMMENT 'OP.Rental Income',
    op_extra_gain                     decimal(18,2)          COMMENT 'OP.Extra Gain',
    op_others                         decimal(18,2)          COMMENT 'OP.Others',
    tot_non_op_expense                decimal(18,2)          COMMENT '*Non-Op. Expense',
    oe_loss_on_a_r_sale               decimal(18,2)          COMMENT 'OE.Loss on A/R Sale',
    oe_extra_loss                     decimal(18,2)          COMMENT 'OE.Extra Loss',
    oe_others                         decimal(18,2)          COMMENT 'OE.Others',
    tot_gain_loss_on_equity           decimal(18,2)          COMMENT '*Gain/Loss on Equity',
    tot_gain_on_equity                decimal(18,2)          COMMENT '*Gain on Equity',
    eg_gain_on_equity                 decimal(18,2)          COMMENT 'EG.Gain on Equity',
    tot_loss_on_equity                decimal(18,2)          COMMENT '*Loss on Equity',
    el_loss_on_equity                 decimal(18,2)          COMMENT 'EL.Loss on Equity',
    tot_financial_income_and_expense  decimal(18,2)          COMMENT '*Financial  Incom. & Exp.',
    tot_finance_profit                decimal(18,2)          COMMENT '*Finance Profit',
    fp_gain_on_fx                     decimal(18,2)          COMMENT 'FP.Gain on FX',
    fp_interest_income                decimal(18,2)          COMMENT 'FP.Interest Income',
    fp_fin_profit_oths                decimal(18,2)          COMMENT 'FP.Fin Profit-Oths',
    tot_finance_loss                  decimal(18,2)          COMMENT '*Finance Loss',
    fe_fo_ex_loss                     decimal(18,2)          COMMENT 'FE.Fo.Ex.Loss',
    fe_interest_exp_ext               decimal(18,2)          COMMENT 'FE.Interest Exp-Ext',
    fe_interest_exp_int               decimal(18,2)          COMMENT 'FE.Interest Exp-Int',
    fe_financial_exp_oth              decimal(18,2)          COMMENT 'FE.Financial Exp-Oth',
    tot_profit_before_tax             decimal(18,2)          COMMENT '*Profit Before Tax',
    tot_corporate_tax                 decimal(18,2)          COMMENT '*Corporate Tax',
    corp_tax                          decimal(18,2)          COMMENT 'Corp. Tax',
    tot_net_income                    decimal(18,2)          COMMENT '*Net Income',

    loaded_at                         datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),

    -- One row per period x customer x material group x profit center.
    -- Loading the same file twice does not pile up duplicates: under
    -- LOAD DATA LOCAL a duplicate key is warning 1062 and the row is skipped.
    UNIQUE KEY ux_pnl_fact_natural (
        fiscal_year, period, sold_to, material_group, profit_center,
        sap_division, distribution_channel, doc_currency
    ),
    KEY ix_pnl_fact_period   (fiscal_year, period),
    KEY ix_pnl_fact_customer (sold_to, fiscal_year, period),
    KEY ix_pnl_fact_matgrp   (material_group, fiscal_year, period)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 ROW_FORMAT=DYNAMIC
  COMMENT='P&L by customer and material group. tot_* are the sheet''s * subtotal lines.';

-- == 3. Load ========
--    Every field is read into a @variable and converted in the SET clause.

LOAD DATA LOCAL INFILE 'C:/work/sales_dashboard/salesDTC/rawdata/sales_2526.csv'
    INTO TABLE pnl_fact
    CHARACTER SET utf8mb4   -- error 1300 means the file is not UTF-8:
                            -- use euckr for a Korean Windows ANSI csv,
                            -- or re-save it from Excel as "CSV UTF-8"
    FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"' ESCAPED BY ''
    LINES TERMINATED BY '\r\n'
    IGNORE 1 LINES          -- skip the header row
(
    @cus_group,
    @record_type,
    @division2,
    @prod_group,
    @fiscal_year,
    @sold_to,
    @forex_rate,
    @sales_usd,
    @op_profit_usd,
    @customer,
    @material_group,
    @nielsen_id,
    @profit_center,
    @sap_division,
    @distribution_channel,
    @period,
    @doc_currency,
    @qty_gross,
    @qty_return,
    @qty_net,
    @tot_s_rrp,
    @reference_price,
    @tot_dealer_discount,
    @s_base_margin,
    @s_contract_margin,
    @s_additional_margin,
    @s_special_margin,
    @tot_s_gross_sales,
    @s_gross_sales_amt,
    @s_other_sales,
    @s_oth_sales_tax_inc,
    @s_internal_sales_amt,
    @tot_s_return_amt,
    @s_return_amt,
    @tot_ref_sales,
    @s_ifc,
    @s_fob_sales_amt,
    @tot_sales_deduction,
    @s_sales_allowance,
    @s_rebate,
    @s_cash_discount,
    @s_price_protection,
    @s_co_op,
    @s_sale_deduction_tax,
    @tot_net_sales,
    @tot_cogs,
    @tot_material_cost,
    @sc_material_cost,
    @sc_matl_cost_loss,
    @sc_cctr_matl_cost,
    @sc_cctr_matl_loss,
    @sc_os_material_cost,
    @sc_other_matl_cost,
    @tot_labor_cost,
    @sc_labor_cost,
    @sc_labor_salaries,
    @sc_labor_overtime,
    @sc_labor_cost_ps,
    @sc_labor_cost_rd,
    @tot_depreciation_exp,
    @sc_depre_exp,
    @sc_depre_exp_on_bldg,
    @sc_depre_exp_on_m_and_e,
    @tot_mold_exp,
    @sc_depre_exp_on_mold,
    @sc_molds_cost,
    @sc_cnc_molds_cost,
    @tot_manufac_supp_cost,
    @sc_mfg_supply_cost,
    @sc_mfg_repair_and_maint,
    @sc_manufac_jig_cost,
    @sc_equip_repair_cost,
    @sc_supplies_exp,
    @tot_expense,
    @sc_amort_on_dev_cost,
    @sc_subcont_cost,
    @sc_part_time_svc_exp,
    @sc_royalty_3rd_party,
    @sc_royalty_hq,
    @sc_utility,
    @sc_logistic_cost,
    @sc_commission,
    @sc_it_cost,
    @sc_installation,
    @sc_tax_and_dues,
    @sc_telecom_exp,
    @sc_travel_exp,
    @sc_rent_and_lease_exp,
    @sc_sample_exp,
    @sc_packing_exp,
    @sc_insurance_premium,
    @sc_convention_exp,
    @sc_svc_exp,
    @sc_other_exps,
    @sc_consumable_rd,
    @sc_ordinary_exp_matl,
    @sc_outsourcing_svc,
    @sc_others_rd,
    @tot_other_cgs,
    @sc_other,
    @sc_svc_warranty,
    @sc_svc_agent_fee,
    @tot_return_cgs,
    @sc_return_cgs,
    @tot_other_expense,
    @tot_other_exp_detail,
    @sc_lcm,
    @sc_e_and_o,
    @sc_ramp_up_cost,
    @sc_inv_loss_q,
    @sc_inv_loss_p,
    @sc_subcontractor_adj,
    @sc_customs_refund,
    @sc_matl_price_settle,
    @sc_vat_china,
    @sc_cgs_others,
    @tot_logistic_cost_c_type,
    @sc_transport_inland,
    @sc_transport_marine,
    @sc_transport_air,
    @sc_transport_other,
    @sc_insurance_logis,
    @tot_internal_cgs,
    @sc_internal_cgs,
    @tot_ref_cogs,
    @sc_stat_customs_fee,
    @sc_stat_incidental,
    @sc_stat_sub_line_exp,
    @tot_gross_margin,
    @tot_operating_expense,
    @tot_sales_expense,
    @tot_labor_cost_s,
    @sa_labor_cost,
    @sa_labor_salaries,
    @tot_svc_expense,
    @sa_svc_warranty,
    @sa_svc_qual_support,
    @sa_svc_agency_fee,
    @sa_svc_call_center,
    @sa_svc_claim,
    @sa_svc_freight,
    @sa_svc_circulation,
    @sa_svc_op_support,
    @sa_svc_other_exp,
    @tot_logistics_cost,
    @sa_transport_inland,
    @sa_transport_marine,
    @sa_transport_air,
    @sa_transport_other,
    @sa_warehouse_fee,
    @sa_insurance_logis,
    @sa_comm,
    @tot_marketing_expense,
    @sa_advertising,
    @sa_co_op,
    @sa_promotion,
    @sa_market_research,
    @sa_sales_commission,
    @sa_comm_and_svcchgc_card,
    @sa_hq_sales_comm,
    @sa_corp_promotion,
    @tot_royalty,
    @sa_royalty_3rd_party,
    @sa_royalty_hq,
    @sa_royalty_lump_sum,
    @tot_paid_commission,
    @sa_comm_consult,
    @sa_comm_litigation,
    @sa_comm_audit,
    @sa_comm_d_o,
    @sa_paid_comm,
    @tot_other_expense_s,
    @sa_depreciation,
    @sa_insurance_premium,
    @sa_sample,
    @sa_it_exp,
    @sa_lease_and_rent,
    @sa_bad_debt_exp,
    @sa_travel_exp,
    @sa_telecom_exp,
    @sa_event_exp,
    @sa_survey_exp,
    @sa_social_exp,
    @sa_convention_exp,
    @sa_copyright,
    @sa_weee,
    @sa_familynet,
    @sa_other_exp,
    @tot_r_and_d_expense,
    @tot_internal_expense,
    @rd_ordinary_exp_matl,
    @rd_labor,
    @rd_depreciation,
    @rd_consumable,
    @rd_others,
    @rd_er,
    @rd_mask,
    @tot_external_expense,
    @rd_royalty,
    @rd_outsourcing_svc,
    @tot_g_and_a_expense,
    @tot_labor_cost_sa,
    @ga_labor_cost,
    @ga_labor_salaries,
    @tot_paid_commission_sa,
    @ga_comm_consult,
    @ga_comm_litigation,
    @ga_comm_audit,
    @ga_comm_d_o,
    @ga_comm,
    @tot_expense_s,
    @ga_depreciation,
    @ga_it_exp,
    @ga_rent_exp,
    @ga_telecom_exp,
    @ga_repairs_and_maint_exp,
    @ga_travel_exp,
    @ga_insurance_premium,
    @ga_convention_exp,
    @ga_other,
    @tot_operating_profit,
    @tot_non_op_income_and_expense,
    @tot_non_op_income,
    @op_commission_3rd,
    @op_service_claim,
    @op_rental_income,
    @op_extra_gain,
    @op_others,
    @tot_non_op_expense,
    @oe_loss_on_a_r_sale,
    @oe_extra_loss,
    @oe_others,
    @tot_gain_loss_on_equity,
    @tot_gain_on_equity,
    @eg_gain_on_equity,
    @tot_loss_on_equity,
    @el_loss_on_equity,
    @tot_financial_income_and_expense,
    @tot_finance_profit,
    @fp_gain_on_fx,
    @fp_interest_income,
    @fp_fin_profit_oths,
    @tot_finance_loss,
    @fe_fo_ex_loss,
    @fe_interest_exp_ext,
    @fe_interest_exp_int,
    @fe_financial_exp_oth,
    @tot_profit_before_tax,
    @tot_corporate_tax,
    @corp_tax,
    @tot_net_income
)
SET
    cus_group = to_txt(@cus_group),
    record_type = to_txt(@record_type),
    division2 = to_txt(@division2),
    prod_group = to_txt(@prod_group),
    fiscal_year = to_num(@fiscal_year),
    sold_to = to_txt(@sold_to),
    forex_rate = to_num(@forex_rate),
    sales_usd = to_num(@sales_usd),
    op_profit_usd = to_num(@op_profit_usd),
    customer = to_txt(@customer),
    material_group = to_txt(@material_group),
    nielsen_id = to_txt(@nielsen_id),
    profit_center = to_txt(@profit_center),
    sap_division = to_txt(@sap_division),
    distribution_channel = to_txt(@distribution_channel),
    period = to_txt(@period),
    doc_currency = to_txt(@doc_currency),
    qty_gross = to_num(@qty_gross),
    qty_return = to_num(@qty_return),
    qty_net = to_num(@qty_net),
    tot_s_rrp = to_num(@tot_s_rrp),
    reference_price = to_num(@reference_price),
    tot_dealer_discount = to_num(@tot_dealer_discount),
    s_base_margin = to_num(@s_base_margin),
    s_contract_margin = to_num(@s_contract_margin),
    s_additional_margin = to_num(@s_additional_margin),
    s_special_margin = to_num(@s_special_margin),
    tot_s_gross_sales = to_num(@tot_s_gross_sales),
    s_gross_sales_amt = to_num(@s_gross_sales_amt),
    s_other_sales = to_num(@s_other_sales),
    s_oth_sales_tax_inc = to_num(@s_oth_sales_tax_inc),
    s_internal_sales_amt = to_num(@s_internal_sales_amt),
    tot_s_return_amt = to_num(@tot_s_return_amt),
    s_return_amt = to_num(@s_return_amt),
    tot_ref_sales = to_num(@tot_ref_sales),
    s_ifc = to_num(@s_ifc),
    s_fob_sales_amt = to_num(@s_fob_sales_amt),
    tot_sales_deduction = to_num(@tot_sales_deduction),
    s_sales_allowance = to_num(@s_sales_allowance),
    s_rebate = to_num(@s_rebate),
    s_cash_discount = to_num(@s_cash_discount),
    s_price_protection = to_num(@s_price_protection),
    s_co_op = to_num(@s_co_op),
    s_sale_deduction_tax = to_num(@s_sale_deduction_tax),
    tot_net_sales = to_num(@tot_net_sales),
    tot_cogs = to_num(@tot_cogs),
    tot_material_cost = to_num(@tot_material_cost),
    sc_material_cost = to_num(@sc_material_cost),
    sc_matl_cost_loss = to_num(@sc_matl_cost_loss),
    sc_cctr_matl_cost = to_num(@sc_cctr_matl_cost),
    sc_cctr_matl_loss = to_num(@sc_cctr_matl_loss),
    sc_os_material_cost = to_num(@sc_os_material_cost),
    sc_other_matl_cost = to_num(@sc_other_matl_cost),
    tot_labor_cost = to_num(@tot_labor_cost),
    sc_labor_cost = to_num(@sc_labor_cost),
    sc_labor_salaries = to_num(@sc_labor_salaries),
    sc_labor_overtime = to_num(@sc_labor_overtime),
    sc_labor_cost_ps = to_num(@sc_labor_cost_ps),
    sc_labor_cost_rd = to_num(@sc_labor_cost_rd),
    tot_depreciation_exp = to_num(@tot_depreciation_exp),
    sc_depre_exp = to_num(@sc_depre_exp),
    sc_depre_exp_on_bldg = to_num(@sc_depre_exp_on_bldg),
    sc_depre_exp_on_m_and_e = to_num(@sc_depre_exp_on_m_and_e),
    tot_mold_exp = to_num(@tot_mold_exp),
    sc_depre_exp_on_mold = to_num(@sc_depre_exp_on_mold),
    sc_molds_cost = to_num(@sc_molds_cost),
    sc_cnc_molds_cost = to_num(@sc_cnc_molds_cost),
    tot_manufac_supp_cost = to_num(@tot_manufac_supp_cost),
    sc_mfg_supply_cost = to_num(@sc_mfg_supply_cost),
    sc_mfg_repair_and_maint = to_num(@sc_mfg_repair_and_maint),
    sc_manufac_jig_cost = to_num(@sc_manufac_jig_cost),
    sc_equip_repair_cost = to_num(@sc_equip_repair_cost),
    sc_supplies_exp = to_num(@sc_supplies_exp),
    tot_expense = to_num(@tot_expense),
    sc_amort_on_dev_cost = to_num(@sc_amort_on_dev_cost),
    sc_subcont_cost = to_num(@sc_subcont_cost),
    sc_part_time_svc_exp = to_num(@sc_part_time_svc_exp),
    sc_royalty_3rd_party = to_num(@sc_royalty_3rd_party),
    sc_royalty_hq = to_num(@sc_royalty_hq),
    sc_utility = to_num(@sc_utility),
    sc_logistic_cost = to_num(@sc_logistic_cost),
    sc_commission = to_num(@sc_commission),
    sc_it_cost = to_num(@sc_it_cost),
    sc_installation = to_num(@sc_installation),
    sc_tax_and_dues = to_num(@sc_tax_and_dues),
    sc_telecom_exp = to_num(@sc_telecom_exp),
    sc_travel_exp = to_num(@sc_travel_exp),
    sc_rent_and_lease_exp = to_num(@sc_rent_and_lease_exp),
    sc_sample_exp = to_num(@sc_sample_exp),
    sc_packing_exp = to_num(@sc_packing_exp),
    sc_insurance_premium = to_num(@sc_insurance_premium),
    sc_convention_exp = to_num(@sc_convention_exp),
    sc_svc_exp = to_num(@sc_svc_exp),
    sc_other_exps = to_num(@sc_other_exps),
    sc_consumable_rd = to_num(@sc_consumable_rd),
    sc_ordinary_exp_matl = to_num(@sc_ordinary_exp_matl),
    sc_outsourcing_svc = to_num(@sc_outsourcing_svc),
    sc_others_rd = to_num(@sc_others_rd),
    tot_other_cgs = to_num(@tot_other_cgs),
    sc_other = to_num(@sc_other),
    sc_svc_warranty = to_num(@sc_svc_warranty),
    sc_svc_agent_fee = to_num(@sc_svc_agent_fee),
    tot_return_cgs = to_num(@tot_return_cgs),
    sc_return_cgs = to_num(@sc_return_cgs),
    tot_other_expense = to_num(@tot_other_expense),
    tot_other_exp_detail = to_num(@tot_other_exp_detail),
    sc_lcm = to_num(@sc_lcm),
    sc_e_and_o = to_num(@sc_e_and_o),
    sc_ramp_up_cost = to_num(@sc_ramp_up_cost),
    sc_inv_loss_q = to_num(@sc_inv_loss_q),
    sc_inv_loss_p = to_num(@sc_inv_loss_p),
    sc_subcontractor_adj = to_num(@sc_subcontractor_adj),
    sc_customs_refund = to_num(@sc_customs_refund),
    sc_matl_price_settle = to_num(@sc_matl_price_settle),
    sc_vat_china = to_num(@sc_vat_china),
    sc_cgs_others = to_num(@sc_cgs_others),
    tot_logistic_cost_c_type = to_num(@tot_logistic_cost_c_type),
    sc_transport_inland = to_num(@sc_transport_inland),
    sc_transport_marine = to_num(@sc_transport_marine),
    sc_transport_air = to_num(@sc_transport_air),
    sc_transport_other = to_num(@sc_transport_other),
    sc_insurance_logis = to_num(@sc_insurance_logis),
    tot_internal_cgs = to_num(@tot_internal_cgs),
    sc_internal_cgs = to_num(@sc_internal_cgs),
    tot_ref_cogs = to_num(@tot_ref_cogs),
    sc_stat_customs_fee = to_num(@sc_stat_customs_fee),
    sc_stat_incidental = to_num(@sc_stat_incidental),
    sc_stat_sub_line_exp = to_num(@sc_stat_sub_line_exp),
    tot_gross_margin = to_num(@tot_gross_margin),
    tot_operating_expense = to_num(@tot_operating_expense),
    tot_sales_expense = to_num(@tot_sales_expense),
    tot_labor_cost_s = to_num(@tot_labor_cost_s),
    sa_labor_cost = to_num(@sa_labor_cost),
    sa_labor_salaries = to_num(@sa_labor_salaries),
    tot_svc_expense = to_num(@tot_svc_expense),
    sa_svc_warranty = to_num(@sa_svc_warranty),
    sa_svc_qual_support = to_num(@sa_svc_qual_support),
    sa_svc_agency_fee = to_num(@sa_svc_agency_fee),
    sa_svc_call_center = to_num(@sa_svc_call_center),
    sa_svc_claim = to_num(@sa_svc_claim),
    sa_svc_freight = to_num(@sa_svc_freight),
    sa_svc_circulation = to_num(@sa_svc_circulation),
    sa_svc_op_support = to_num(@sa_svc_op_support),
    sa_svc_other_exp = to_num(@sa_svc_other_exp),
    tot_logistics_cost = to_num(@tot_logistics_cost),
    sa_transport_inland = to_num(@sa_transport_inland),
    sa_transport_marine = to_num(@sa_transport_marine),
    sa_transport_air = to_num(@sa_transport_air),
    sa_transport_other = to_num(@sa_transport_other),
    sa_warehouse_fee = to_num(@sa_warehouse_fee),
    sa_insurance_logis = to_num(@sa_insurance_logis),
    sa_comm = to_num(@sa_comm),
    tot_marketing_expense = to_num(@tot_marketing_expense),
    sa_advertising = to_num(@sa_advertising),
    sa_co_op = to_num(@sa_co_op),
    sa_promotion = to_num(@sa_promotion),
    sa_market_research = to_num(@sa_market_research),
    sa_sales_commission = to_num(@sa_sales_commission),
    sa_comm_and_svcchgc_card = to_num(@sa_comm_and_svcchgc_card),
    sa_hq_sales_comm = to_num(@sa_hq_sales_comm),
    sa_corp_promotion = to_num(@sa_corp_promotion),
    tot_royalty = to_num(@tot_royalty),
    sa_royalty_3rd_party = to_num(@sa_royalty_3rd_party),
    sa_royalty_hq = to_num(@sa_royalty_hq),
    sa_royalty_lump_sum = to_num(@sa_royalty_lump_sum),
    tot_paid_commission = to_num(@tot_paid_commission),
    sa_comm_consult = to_num(@sa_comm_consult),
    sa_comm_litigation = to_num(@sa_comm_litigation),
    sa_comm_audit = to_num(@sa_comm_audit),
    sa_comm_d_o = to_num(@sa_comm_d_o),
    sa_paid_comm = to_num(@sa_paid_comm),
    tot_other_expense_s = to_num(@tot_other_expense_s),
    sa_depreciation = to_num(@sa_depreciation),
    sa_insurance_premium = to_num(@sa_insurance_premium),
    sa_sample = to_num(@sa_sample),
    sa_it_exp = to_num(@sa_it_exp),
    sa_lease_and_rent = to_num(@sa_lease_and_rent),
    sa_bad_debt_exp = to_num(@sa_bad_debt_exp),
    sa_travel_exp = to_num(@sa_travel_exp),
    sa_telecom_exp = to_num(@sa_telecom_exp),
    sa_event_exp = to_num(@sa_event_exp),
    sa_survey_exp = to_num(@sa_survey_exp),
    sa_social_exp = to_num(@sa_social_exp),
    sa_convention_exp = to_num(@sa_convention_exp),
    sa_copyright = to_num(@sa_copyright),
    sa_weee = to_num(@sa_weee),
    sa_familynet = to_num(@sa_familynet),
    sa_other_exp = to_num(@sa_other_exp),
    tot_r_and_d_expense = to_num(@tot_r_and_d_expense),
    tot_internal_expense = to_num(@tot_internal_expense),
    rd_ordinary_exp_matl = to_num(@rd_ordinary_exp_matl),
    rd_labor = to_num(@rd_labor),
    rd_depreciation = to_num(@rd_depreciation),
    rd_consumable = to_num(@rd_consumable),
    rd_others = to_num(@rd_others),
    rd_er = to_num(@rd_er),
    rd_mask = to_num(@rd_mask),
    tot_external_expense = to_num(@tot_external_expense),
    rd_royalty = to_num(@rd_royalty),
    rd_outsourcing_svc = to_num(@rd_outsourcing_svc),
    tot_g_and_a_expense = to_num(@tot_g_and_a_expense),
    tot_labor_cost_sa = to_num(@tot_labor_cost_sa),
    ga_labor_cost = to_num(@ga_labor_cost),
    ga_labor_salaries = to_num(@ga_labor_salaries),
    tot_paid_commission_sa = to_num(@tot_paid_commission_sa),
    ga_comm_consult = to_num(@ga_comm_consult),
    ga_comm_litigation = to_num(@ga_comm_litigation),
    ga_comm_audit = to_num(@ga_comm_audit),
    ga_comm_d_o = to_num(@ga_comm_d_o),
    ga_comm = to_num(@ga_comm),
    tot_expense_s = to_num(@tot_expense_s),
    ga_depreciation = to_num(@ga_depreciation),
    ga_it_exp = to_num(@ga_it_exp),
    ga_rent_exp = to_num(@ga_rent_exp),
    ga_telecom_exp = to_num(@ga_telecom_exp),
    ga_repairs_and_maint_exp = to_num(@ga_repairs_and_maint_exp),
    ga_travel_exp = to_num(@ga_travel_exp),
    ga_insurance_premium = to_num(@ga_insurance_premium),
    ga_convention_exp = to_num(@ga_convention_exp),
    ga_other = to_num(@ga_other),
    tot_operating_profit = to_num(@tot_operating_profit),
    tot_non_op_income_and_expense = to_num(@tot_non_op_income_and_expense),
    tot_non_op_income = to_num(@tot_non_op_income),
    op_commission_3rd = to_num(@op_commission_3rd),
    op_service_claim = to_num(@op_service_claim),
    op_rental_income = to_num(@op_rental_income),
    op_extra_gain = to_num(@op_extra_gain),
    op_others = to_num(@op_others),
    tot_non_op_expense = to_num(@tot_non_op_expense),
    oe_loss_on_a_r_sale = to_num(@oe_loss_on_a_r_sale),
    oe_extra_loss = to_num(@oe_extra_loss),
    oe_others = to_num(@oe_others),
    tot_gain_loss_on_equity = to_num(@tot_gain_loss_on_equity),
    tot_gain_on_equity = to_num(@tot_gain_on_equity),
    eg_gain_on_equity = to_num(@eg_gain_on_equity),
    tot_loss_on_equity = to_num(@tot_loss_on_equity),
    el_loss_on_equity = to_num(@el_loss_on_equity),
    tot_financial_income_and_expense = to_num(@tot_financial_income_and_expense),
    tot_finance_profit = to_num(@tot_finance_profit),
    fp_gain_on_fx = to_num(@fp_gain_on_fx),
    fp_interest_income = to_num(@fp_interest_income),
    fp_fin_profit_oths = to_num(@fp_fin_profit_oths),
    tot_finance_loss = to_num(@tot_finance_loss),
    fe_fo_ex_loss = to_num(@fe_fo_ex_loss),
    fe_interest_exp_ext = to_num(@fe_interest_exp_ext),
    fe_interest_exp_int = to_num(@fe_interest_exp_int),
    fe_financial_exp_oth = to_num(@fe_financial_exp_oth),
    tot_profit_before_tax = to_num(@tot_profit_before_tax),
    tot_corporate_tax = to_num(@tot_corporate_tax),
    corp_tax = to_num(@corp_tax),
    tot_net_income = to_num(@tot_net_income);

-- == 4. Verify ========

SELECT count(*) AS loaded_rows FROM pnl_fact;
SHOW WARNINGS;

-- Eyeball a few rows to confirm values landed in the right columns.
SELECT sold_to, material_group, prod_group, period,
       tot_net_sales, tot_cogs, tot_gross_margin, tot_operating_profit
FROM   pnl_fact
LIMIT  5;

-- Reconciliation: all four counters must be 0.
--   non-zero -> columns are shifted
--   NULL     -> nothing parsed at all, so the delimiter, line ending or
--               character set is wrong. Run 08_probe_file.sql.
SELECT
    sum(abs(tot_net_sales - (tot_s_gross_sales - tot_sales_deduction)) > 0.05) AS err_net_sales,
    sum(abs(tot_gross_margin - (tot_net_sales - tot_cogs)) > 0.05) AS err_gross_margin,
    sum(abs(tot_operating_expense - (tot_sales_expense + tot_r_and_d_expense + tot_g_and_a_expense)) > 0.05) AS err_op_expense,
    sum(abs(tot_operating_profit - (tot_gross_margin - tot_operating_expense)) > 0.05) AS err_op_profit
FROM pnl_fact;
