-- MySQL 판. 엑셀 원본 251 컬럼 그대로.
-- tot_* 는 원본에서 * 가 붙은 소계 라인이다 (하위 계정의 합계이므로 중복 집계 주의).
-- MySQL 은 스키마와 DB 가 같은 개념이라 sales 스키마 대신 DB 를 하나 쓴다.
-- 다른 DB 에 넣으려면 아래 두 줄만 바꾸면 된다.

CREATE DATABASE IF NOT EXISTS sales_pnl DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;
USE sales_pnl;

DROP TABLE IF EXISTS pnl_fact;

CREATE TABLE pnl_fact (
    pnl_id           bigint NOT NULL AUTO_INCREMENT PRIMARY KEY,

    -- ══ 헤더/집계 키 (엑셀 좌측 블록) ════════
    cus_group                         varchar(20)            COMMENT 'Cus_group',
    record_type                       varchar(10)            COMMENT 'Type',
    division2                         varchar(20)            COMMENT 'Division 2',
    prod_group                        varchar(20)            COMMENT 'Prod_group',
    fiscal_year                       smallint NOT NULL      COMMENT 'Year',
    sold_to                           varchar(20)            COMMENT 'sold To',
    forex_rate                        decimal(18,9)          COMMENT 'Forex',
    sales_usd                         decimal(18,2)          COMMENT 'Sales U$',
    op_profit_usd                     decimal(18,2)          COMMENT 'Op Profit U$',

    -- ══ SAP 원장 차원 (Dimension) ════════
    customer                          varchar(20)            COMMENT 'Customer',
    material_group                    varchar(20)            COMMENT 'Material Group',
    nielsen_id                        varchar(20)            COMMENT 'Nielsen ID',
    profit_center                     varchar(20)            COMMENT 'Profit Center',
    sap_division                      varchar(10)            COMMENT 'Division',
    distribution_channel              varchar(10)            COMMENT 'Distribution Channel',
    period                            varchar(10) NOT NULL   COMMENT 'Period',
    doc_currency                      varchar(10)            COMMENT 'Currency',

    -- ══ 수량 (Quantity) ════════
    qty_gross                         decimal(18,3)          COMMENT 'Quantity(Gross)',
    qty_return                        decimal(18,3)          COMMENT 'Quantity(Return)',
    qty_net                           decimal(18,3)          COMMENT 'Quantity(Net)',

    -- ══ 매출 (Sales) ════════
    tot_s_rrp                         decimal(18,2)          COMMENT '*S.RRP',
    reference_price                   decimal(18,2)          COMMENT 'Reference Price',
    tot_dealer_discount               decimal(18,2)          COMMENT '*Delear Discount',
    s_base_margin                     decimal(18,2)          COMMENT 'S.Base Margin',
    s_contract_margin                 decimal(18,2)          COMMENT 'S.Contract Margin',
    s_additional_margin               decimal(18,2)          COMMENT 'S.Additional Margin',
    s_special_margin                  decimal(18,2)          COMMENT 'S.Special Margin',
    tot_s_gross_sales                 decimal(18,2)          COMMENT '*S.Gross Sales',
    s_gross_sales_amt                 decimal(18,2)          COMMENT 'S.Gross Sales AMT',
    s_other_sales                     decimal(18,2)          COMMENT 'S.Other Sales',
    s_oth_sales_tax_inc               decimal(18,2)          COMMENT 'S.Oth Sales Tax Inc',
    s_internal_sales_amt              decimal(18,2)          COMMENT 'S.Internal Sales Amt',
    tot_s_return_amt                  decimal(18,2)          COMMENT '*S.Return Amt',
    s_return_amt                      decimal(18,2)          COMMENT 'S.Return Amt',
    tot_ref_sales                     decimal(18,2)          COMMENT '*Ref. Sales',
    s_ifc                             decimal(18,2)          COMMENT 'S.IFC',
    s_fob_sales_amt                   decimal(18,2)          COMMENT 'S.FOB Sales Amt',
    tot_sales_deduction               decimal(18,2)          COMMENT '*Sales Deduction',
    s_sales_allowance                 decimal(18,2)          COMMENT 'S.Sales Allowance',
    s_rebate                          decimal(18,2)          COMMENT 'S.Rebate',
    s_cash_discount                   decimal(18,2)          COMMENT 'S.Cash Discount',
    s_price_protection                decimal(18,2)          COMMENT 'S.Price Protection',
    s_co_op                           decimal(18,2)          COMMENT 'S.CO-OP',
    s_sale_deduction_tax              decimal(18,2)          COMMENT 'S.Sale Deduction TAX',
    tot_net_sales                     decimal(18,2)          COMMENT '*Net Sales',

    -- ══ 매출원가 (Cost of Goods Sold) ════════
    tot_cogs                          decimal(18,2)          COMMENT '*Cost of Goods Sold',
    tot_material_cost                 decimal(18,2)          COMMENT '*Material Cost',
    sc_material_cost                  decimal(18,2)          COMMENT 'SC.Material Cost',
    sc_matl_cost_loss                 decimal(18,2)          COMMENT 'SC.Matl Cost-Loss',
    sc_cctr_matl_cost                 decimal(18,2)          COMMENT 'SC.Cctr Matl Cost',
    sc_cctr_matl_loss                 decimal(18,2)          COMMENT 'SC.Cctr Matl-Loss',
    sc_os_material_cost               decimal(18,2)          COMMENT 'SC.OS Material Cost',
    sc_other_matl_cost                decimal(18,2)          COMMENT 'SC.Other Matl Cost',
    tot_labor_cost                    decimal(18,2)          COMMENT '*Labor Cost',
    sc_labor_cost                     decimal(18,2)          COMMENT 'SC.Labor Cost',
    sc_labor_salaries                 decimal(18,2)          COMMENT 'SC.Labor-Salaries',
    sc_labor_overtime                 decimal(18,2)          COMMENT 'SC.Labor-Overtime',
    sc_labor_cost_ps                  decimal(18,2)          COMMENT 'SC.Labor Cost(PS)',
    sc_labor_cost_rd                  decimal(18,2)          COMMENT 'SC.Labor Cost(RD)',
    tot_depreciation_exp              decimal(18,2)          COMMENT '*Depreciation Exp',
    sc_depre_exp                      decimal(18,2)          COMMENT 'SC.Depre Exp',
    sc_depre_exp_on_bldg              decimal(18,2)          COMMENT 'SC.Depre Exp on Bldg',
    sc_depre_exp_on_m_and_e           decimal(18,2)          COMMENT 'SC.Depre Exp on M&E',
    tot_mold_exp                      decimal(18,2)          COMMENT '*Mold Exp',
    sc_depre_exp_on_mold              decimal(18,2)          COMMENT 'SC.Depre Exp on Mold',
    sc_molds_cost                     decimal(18,2)          COMMENT 'SC.Molds Cost',
    sc_cnc_molds_cost                 decimal(18,2)          COMMENT 'SC.CNC Molds Cost',
    tot_manufac_supp_cost             decimal(18,2)          COMMENT '*Manufac.supp.Cost',
    sc_mfg_supply_cost                decimal(18,2)          COMMENT 'SC.Mfg Supply Cost',
    sc_mfg_repair_and_maint           decimal(18,2)          COMMENT 'SC.Mfg Repair&Maint',
    sc_manufac_jig_cost               decimal(18,2)          COMMENT 'SC.Manufac.JIG.Cost',
    sc_equip_repair_cost              decimal(18,2)          COMMENT 'SC.Equip Repair Cost',
    sc_supplies_exp                   decimal(18,2)          COMMENT 'SC.Supplies Exp',
    tot_expense                       decimal(18,2)          COMMENT '*Expense',
    sc_amort_on_dev_cost              decimal(18,2)          COMMENT 'SC.Amort on Dev Cost',
    sc_subcont_cost                   decimal(18,2)          COMMENT 'SC.Subcont. Cost',
    sc_part_time_svc_exp              decimal(18,2)          COMMENT 'SC.Part Time SVC Exp',
    sc_royalty_3rd_party              decimal(18,2)          COMMENT 'SC.Royalty-3rd Party',
    sc_royalty_hq                     decimal(18,2)          COMMENT 'SC.Royalty-HQ',
    sc_utility                        decimal(18,2)          COMMENT 'SC.Utility',
    sc_logistic_cost                  decimal(18,2)          COMMENT 'SC.Logistic Cost',
    sc_commission                     decimal(18,2)          COMMENT 'SC.Commission',
    sc_it_cost                        decimal(18,2)          COMMENT 'SC.IT Cost',
    sc_installation                   decimal(18,2)          COMMENT 'SC.Installation',
    sc_tax_and_dues                   decimal(18,2)          COMMENT 'SC.Tax&Dues',
    sc_telecom_exp                    decimal(18,2)          COMMENT 'SC.Telecom Exp',
    sc_travel_exp                     decimal(18,2)          COMMENT 'SC.Travel Exp',
    sc_rent_and_lease_exp             decimal(18,2)          COMMENT 'SC.Rent&Lease Exp',
    sc_sample_exp                     decimal(18,2)          COMMENT 'SC.Sample Exp',
    sc_packing_exp                    decimal(18,2)          COMMENT 'SC.Packing Exp',
    sc_insurance_premium              decimal(18,2)          COMMENT 'SC.Insurance Premium',
    sc_convention_exp                 decimal(18,2)          COMMENT 'SC.Convention Exp',
    sc_svc_exp                        decimal(18,2)          COMMENT 'SC.SVC Exp',
    sc_other_exps                     decimal(18,2)          COMMENT 'SC.Other Exps',
    sc_consumable_rd                  decimal(18,2)          COMMENT 'SC.Consumable(RD)',
    sc_ordinary_exp_matl              decimal(18,2)          COMMENT 'SC.Ordinary Exp-Matl',
    sc_outsourcing_svc                decimal(18,2)          COMMENT 'SC.Outsourcing SVC',
    sc_others_rd                      decimal(18,2)          COMMENT 'SC.Othres(RD)',
    tot_other_cgs                     decimal(18,2)          COMMENT '*Other CGS',
    sc_other                          decimal(18,2)          COMMENT 'SC.Other',
    sc_svc_warranty                   decimal(18,2)          COMMENT 'SC.SVC Warranty',
    sc_svc_agent_fee                  decimal(18,2)          COMMENT 'SC.SVC Agent Fee',
    tot_return_cgs                    decimal(18,2)          COMMENT '*Return CGS',
    sc_return_cgs                     decimal(18,2)          COMMENT 'SC.Return CGS',
    tot_other_expense                 decimal(18,2)          COMMENT '*Other Expense',
    tot_other_exp_detail              decimal(18,2)          COMMENT '*Other Exp.',
    sc_lcm                            decimal(18,2)          COMMENT 'SC.LCM',
    sc_e_and_o                        decimal(18,2)          COMMENT 'SC.E&O',
    sc_ramp_up_cost                   decimal(18,2)          COMMENT 'SC.Ramp-up Cost',
    sc_inv_loss_q                     decimal(18,2)          COMMENT 'SC.INV Loss(Q)',
    sc_inv_loss_p                     decimal(18,2)          COMMENT 'SC.INV Loss(P)',
    sc_subcontractor_adj              decimal(18,2)          COMMENT 'SC.Subcontractor-Adj',
    sc_customs_refund                 decimal(18,2)          COMMENT 'SC.Customs Refund',
    sc_matl_price_settle              decimal(18,2)          COMMENT 'SC.Matl Price Settle',
    sc_vat_china                      decimal(18,2)          COMMENT 'SC.VAT (China)',
    sc_cgs_others                     decimal(18,2)          COMMENT 'SC.CGS Others',
    tot_logistic_cost_c_type          decimal(18,2)          COMMENT '*Logistic Cost(C Type)',
    sc_transport_inland               decimal(18,2)          COMMENT 'SC.Transport-Inland',
    sc_transport_marine               decimal(18,2)          COMMENT 'SC.Transport-Marine',
    sc_transport_air                  decimal(18,2)          COMMENT 'SC.Transport-Air',
    sc_transport_other                decimal(18,2)          COMMENT 'SC.Transport-Other',
    sc_insurance_logis                decimal(18,2)          COMMENT 'SC.Insurance (Logis)',
    tot_internal_cgs                  decimal(18,2)          COMMENT '*Internal CGS',
    sc_internal_cgs                   decimal(18,2)          COMMENT 'SC.Internal CGS',
    tot_ref_cogs                      decimal(18,2)          COMMENT '*Ref. CoGS',
    sc_stat_customs_fee               decimal(18,2)          COMMENT 'SC.Stat.Customs Fee',
    sc_stat_incidental                decimal(18,2)          COMMENT 'SC.Stat Incidental',
    sc_stat_sub_line_exp              decimal(18,2)          COMMENT 'SC.Stat.Sub-Line Exp',

    -- ══ 매출총이익 / 판관비 (Gross Margin & Operating Expense) ════════
    tot_gross_margin                  decimal(18,2)          COMMENT '*Gross Margin',
    tot_operating_expense             decimal(18,2)          COMMENT '*Operating Expense',
    tot_sales_expense                 decimal(18,2)          COMMENT '*Sales Expense',
    tot_labor_cost_s                  decimal(18,2)          COMMENT '*Labor Cost(S)',
    sa_labor_cost                     decimal(18,2)          COMMENT 'SA.Labor Cost',
    sa_labor_salaries                 decimal(18,2)          COMMENT 'SA.Labor-Salaries',
    tot_svc_expense                   decimal(18,2)          COMMENT '*SVC Expense',
    sa_svc_warranty                   decimal(18,2)          COMMENT 'SA.SVC Warranty',
    sa_svc_qual_support               decimal(18,2)          COMMENT 'SA.SVC Qual Support',
    sa_svc_agency_fee                 decimal(18,2)          COMMENT 'SA.SVC Agency Fee',
    sa_svc_call_center                decimal(18,2)          COMMENT 'SA.SVC Call Center',
    sa_svc_claim                      decimal(18,2)          COMMENT 'SA.SVC Claim',
    sa_svc_freight                    decimal(18,2)          COMMENT 'SA.SVC Freight',
    sa_svc_circulation                decimal(18,2)          COMMENT 'SA.SVC Circulation',
    sa_svc_op_support                 decimal(18,2)          COMMENT 'SA.SVC Op Support',
    sa_svc_other_exp                  decimal(18,2)          COMMENT 'SA.SVC Other Exp',
    tot_logistics_cost                decimal(18,2)          COMMENT '*Logistics Cost',
    sa_transport_inland               decimal(18,2)          COMMENT 'SA.Transport-Inland',
    sa_transport_marine               decimal(18,2)          COMMENT 'SA.Transport-Marine',
    sa_transport_air                  decimal(18,2)          COMMENT 'SA.Transport-Air',
    sa_transport_other                decimal(18,2)          COMMENT 'SA.Transport-Other',
    sa_warehouse_fee                  decimal(18,2)          COMMENT 'SA.Warehouse Fee',
    sa_insurance_logis                decimal(18,2)          COMMENT 'SA.Insurance (Logis)',
    sa_comm                           decimal(18,2)          COMMENT 'SA.Comm',
    tot_marketing_expense             decimal(18,2)          COMMENT '*Marketing Expense',
    sa_advertising                    decimal(18,2)          COMMENT 'SA.Advertising',
    sa_co_op                          decimal(18,2)          COMMENT 'SA.CO-OP',
    sa_promotion                      decimal(18,2)          COMMENT 'SA.Promotion',
    sa_market_research                decimal(18,2)          COMMENT 'SA.Market Research',
    sa_sales_commission               decimal(18,2)          COMMENT 'SA.Sales Commission',
    sa_comm_and_svcchgc_card          decimal(18,2)          COMMENT 'SA.Comm&SvcChgC.Card',
    sa_hq_sales_comm                  decimal(18,2)          COMMENT 'SA.HQ Sales Comm',
    sa_corp_promotion                 decimal(18,2)          COMMENT 'SA.Corp. Promotion',
    tot_royalty                       decimal(18,2)          COMMENT '*Royalty',
    sa_royalty_3rd_party              decimal(18,2)          COMMENT 'SA.Royalty-3rd Party',
    sa_royalty_hq                     decimal(18,2)          COMMENT 'SA.Royalty-HQ',
    sa_royalty_lump_sum               decimal(18,2)          COMMENT 'SA.Royalty-Lump Sum',
    tot_paid_commission               decimal(18,2)          COMMENT '*Paid Commission',
    sa_comm_consult                   decimal(18,2)          COMMENT 'SA.Comm-Consult',
    sa_comm_litigation                decimal(18,2)          COMMENT 'SA.Comm-Litigation',
    sa_comm_audit                     decimal(18,2)          COMMENT 'SA.Comm-Audit',
    sa_comm_d_o                       decimal(18,2)          COMMENT 'SA.Comm-D/O',
    sa_paid_comm                      decimal(18,2)          COMMENT 'SA.Paid Comm',
    tot_other_expense_s               decimal(18,2)          COMMENT '*Other Expense(S)',
    sa_depreciation                   decimal(18,2)          COMMENT 'SA.Depreciation',
    sa_insurance_premium              decimal(18,2)          COMMENT 'SA.Insurance Premium',
    sa_sample                         decimal(18,2)          COMMENT 'SA.Sample',
    sa_it_exp                         decimal(18,2)          COMMENT 'SA.IT Exp',
    sa_lease_and_rent                 decimal(18,2)          COMMENT 'SA.Lease&Rent',
    sa_bad_debt_exp                   decimal(18,2)          COMMENT 'SA.Bad Debt Exp',
    sa_travel_exp                     decimal(18,2)          COMMENT 'SA.Travel Exp',
    sa_telecom_exp                    decimal(18,2)          COMMENT 'SA.Telecom Exp',
    sa_event_exp                      decimal(18,2)          COMMENT 'SA.Event Exp',
    sa_survey_exp                     decimal(18,2)          COMMENT 'SA.Survey Exp',
    sa_social_exp                     decimal(18,2)          COMMENT 'SA.Social Exp',
    sa_convention_exp                 decimal(18,2)          COMMENT 'SA.Convention Exp',
    sa_copyright                      decimal(18,2)          COMMENT 'SA.Copyright',
    sa_weee                           decimal(18,2)          COMMENT 'SA.WEEE',
    sa_familynet                      decimal(18,2)          COMMENT 'SA.Familynet',
    sa_other_exp                      decimal(18,2)          COMMENT 'SA.Other Exp',

    -- ══ 연구개발비 (R&D Expense) ════════
    tot_r_and_d_expense               decimal(18,2)          COMMENT '*R&D Expense',
    tot_internal_expense              decimal(18,2)          COMMENT '*Internal Expense',
    rd_ordinary_exp_matl              decimal(18,2)          COMMENT 'RD.Ordinary Exp-Matl',
    rd_labor                          decimal(18,2)          COMMENT 'RD Labor',
    rd_depreciation                   decimal(18,2)          COMMENT 'RD.Depreciation',
    rd_consumable                     decimal(18,2)          COMMENT 'RD.Consumable',
    rd_others                         decimal(18,2)          COMMENT 'RD.Others',
    rd_er                             decimal(18,2)          COMMENT 'RD.ER',
    rd_mask                           decimal(18,2)          COMMENT 'RD.Mask',
    tot_external_expense              decimal(18,2)          COMMENT '*External Expense',
    rd_royalty                        decimal(18,2)          COMMENT 'RD.Royalty',
    rd_outsourcing_svc                decimal(18,2)          COMMENT 'RD.Outsourcing SVC',

    -- ══ 일반관리비 (G&A Expense) ════════
    tot_g_and_a_expense               decimal(18,2)          COMMENT '*G&A Expense',
    tot_labor_cost_sa                 decimal(18,2)          COMMENT '*Labor Cost(SA)',
    ga_labor_cost                     decimal(18,2)          COMMENT 'GA.Labor Cost',
    ga_labor_salaries                 decimal(18,2)          COMMENT 'GA.Labor-Salaries',
    tot_paid_commission_sa            decimal(18,2)          COMMENT '*Paid Commission(SA)',
    ga_comm_consult                   decimal(18,2)          COMMENT 'GA.Comm-Consult',
    ga_comm_litigation                decimal(18,2)          COMMENT 'GA.Comm-Litigation',
    ga_comm_audit                     decimal(18,2)          COMMENT 'GA.Comm-Audit',
    ga_comm_d_o                       decimal(18,2)          COMMENT 'GA.Comm-D/O',
    ga_comm                           decimal(18,2)          COMMENT 'GA.Comm',
    tot_expense_s                     decimal(18,2)          COMMENT '*Expense(S)',
    ga_depreciation                   decimal(18,2)          COMMENT 'GA.Depreciation',
    ga_it_exp                         decimal(18,2)          COMMENT 'GA.IT Exp',
    ga_rent_exp                       decimal(18,2)          COMMENT 'GA.Rent Exp',
    ga_telecom_exp                    decimal(18,2)          COMMENT 'GA.Telecom Exp',
    ga_repairs_and_maint_exp          decimal(18,2)          COMMENT 'GA.Repairs&Maint Exp',
    ga_travel_exp                     decimal(18,2)          COMMENT 'GA.Travel Exp',
    ga_insurance_premium              decimal(18,2)          COMMENT 'GA.Insurance Premium',
    ga_convention_exp                 decimal(18,2)          COMMENT 'GA.Convention Exp',
    ga_other                          decimal(18,2)          COMMENT 'GA.Other',

    -- ══ 영업이익 이하 (Operating Profit & below) ════════
    tot_operating_profit              decimal(18,2)          COMMENT '*Operating Profit',
    tot_non_op_income_and_expense     decimal(18,2)          COMMENT '*Non-Op. Incom. & Ex',
    tot_non_op_income                 decimal(18,2)          COMMENT '*Non-Op. Income',
    op_commission_3rd                 decimal(18,2)          COMMENT 'OP.Commission 3rd',
    op_service_claim                  decimal(18,2)          COMMENT 'OP.Service Claim',
    op_rental_income                  decimal(18,2)          COMMENT 'OP.Rental Income',
    op_extra_gain                     decimal(18,2)          COMMENT 'OP.Extra Gain',
    op_others                         decimal(18,2)          COMMENT 'OP.Others',
    tot_non_op_expense                decimal(18,2)          COMMENT '*Non-Op. Expense',
    oe_loss_on_a_r_sale               decimal(18,2)          COMMENT 'OE.Loss on A/R Sale',
    oe_extra_loss                     decimal(18,2)          COMMENT 'OE.Extra Loss',
    oe_others                         decimal(18,2)          COMMENT 'OE.Others',
    tot_gain_loss_on_equity           decimal(18,2)          COMMENT '*Gain/Loss on Equity',
    tot_gain_on_equity                decimal(18,2)          COMMENT '*Gain on Equity',
    eg_gain_on_equity                 decimal(18,2)          COMMENT 'EG.Gain on Equity',
    tot_loss_on_equity                decimal(18,2)          COMMENT '*Loss on Equity',
    el_loss_on_equity                 decimal(18,2)          COMMENT 'EL.Loss on Equity',
    tot_financial_income_and_expense  decimal(18,2)          COMMENT '*Financial  Incom. & Exp.',
    tot_finance_profit                decimal(18,2)          COMMENT '*Finance Profit',
    fp_gain_on_fx                     decimal(18,2)          COMMENT 'FP.Gain on FX',
    fp_interest_income                decimal(18,2)          COMMENT 'FP.Interest Income',
    fp_fin_profit_oths                decimal(18,2)          COMMENT 'FP.Fin Profit-Oths',
    tot_finance_loss                  decimal(18,2)          COMMENT '*Finance Loss',
    fe_fo_ex_loss                     decimal(18,2)          COMMENT 'FE.Fo.Ex.Loss',
    fe_interest_exp_ext               decimal(18,2)          COMMENT 'FE.Interest Exp-Ext',
    fe_interest_exp_int               decimal(18,2)          COMMENT 'FE.Interest Exp-Int',
    fe_financial_exp_oth              decimal(18,2)          COMMENT 'FE.Financial Exp-Oth',
    tot_profit_before_tax             decimal(18,2)          COMMENT '*Profit Before Tax',
    tot_corporate_tax                 decimal(18,2)          COMMENT '*Corporate Tax',
    corp_tax                          decimal(18,2)          COMMENT 'Corp. Tax',
    tot_net_income                    decimal(18,2)          COMMENT '*Net Income',

    -- ══ 적재 메타데이터 ════════
    source_file                       varchar(260),
    loaded_at                         datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),

    -- 자연키: 같은 기간의 같은 고객 x 제품군 x 손익센터 조합은 1행.
    -- 재적재 시 중복을 막아준다. 키 컬럼에 NULL 이 섞이는 소스라면 이 인덱스를 빼고
    -- 적재 전 DELETE 로 해당 기간을 지우는 방식을 쓸 것.
    UNIQUE KEY ux_pnl_fact_natural (
        fiscal_year, period, sold_to, material_group, profit_center,
        sap_division, distribution_channel, doc_currency
    ),
    KEY ix_pnl_fact_period   (fiscal_year, period),
    KEY ix_pnl_fact_customer (sold_to, fiscal_year, period),
    KEY ix_pnl_fact_matgrp   (material_group, fiscal_year, period)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 ROW_FORMAT=DYNAMIC
  COMMENT='고객/제품군 단위 손익(P&L) 플랫 테이블. tot_* 는 엑셀 원본의 * 소계 라인.';
