-- Cleanup functions plus an all-text staging table holding the raw file.
-- Thousands separators, blanks and #N/A pass through here and are converted
-- by 04_load_from_staging.sql.
--
-- To skip staging entirely, run only the two functions below and use
-- 06_load_direct.sql instead - one step fewer.
USE sales_2526;

-- Excel-style number string -> decimal  ("1,268.93", "(1,234)", "", "-", "#N/A")
-- Anything that is not a plain number becomes NULL rather than raising, so a
-- misaligned file cannot abort the load halfway through. The reconciliation
-- queries at the end are what tell you the file was misaligned.
DROP FUNCTION IF EXISTS to_num;
DROP FUNCTION IF EXISTS to_txt;
DELIMITER $$

CREATE FUNCTION to_num(v text) RETURNS decimal(18,4)
DETERMINISTIC
BEGIN
    DECLARE t varchar(255);
    SET t = LEFT(REPLACE(REPLACE(REPLACE(TRIM(COALESCE(v, '')), ',', ''),
                                 '$', ''), ' ', ''), 255);
    IF t = '' OR t IN ('-', '#N/A', 'N/A', '#DIV/0!', '#VALUE!') THEN
        RETURN NULL;
    END IF;
    IF t LIKE '(%)' THEN                       -- accounting negative (12.50) -> -12.50
        SET t = CONCAT('-', SUBSTRING(t, 2, CHAR_LENGTH(t) - 2));
    END IF;
    IF CHAR_LENGTH(t) > 30 OR t NOT REGEXP '^-?[0-9]*\.?[0-9]+$' THEN
        RETURN NULL;
    END IF;
    RETURN CAST(t AS decimal(18,4));
END$$

-- Dimension text: trim, and turn blank / #N/A into NULL
CREATE FUNCTION to_txt(v text) RETURNS varchar(260)
DETERMINISTIC
BEGIN
    DECLARE t varchar(260);
    SET t = LEFT(TRIM(COALESCE(v, '')), 260);
    IF t = '' OR t = '#N/A' THEN
        RETURN NULL;
    END IF;
    RETURN t;
END$$

DELIMITER ;

-- MySQL 8 refuses a table of 251 text columns because of the InnoDB row size
-- limit (8126 bytes, error 1118). The values are short, so the DYNAMIC row
-- format stores them off-page at runtime; only the create-time check needs
-- to be relaxed.
SET SESSION innodb_strict_mode = OFF;

DROP TABLE IF EXISTS pnl_stg;
CREATE TABLE pnl_stg (
    cus_group                         text,
    record_type                       text,
    division2                         text,
    prod_group                        text,
    fiscal_year                       text,
    sold_to                           text,
    forex_rate                        text,
    sales_usd                         text,
    op_profit_usd                     text,
    customer                          text,
    material_group                    text,
    nielsen_id                        text,
    profit_center                     text,
    sap_division                      text,
    distribution_channel              text,
    period                            text,
    doc_currency                      text,
    qty_gross                         text,
    qty_return                        text,
    qty_net                           text,
    tot_s_rrp                         text,
    reference_price                   text,
    tot_dealer_discount               text,
    s_base_margin                     text,
    s_contract_margin                 text,
    s_additional_margin               text,
    s_special_margin                  text,
    tot_s_gross_sales                 text,
    s_gross_sales_amt                 text,
    s_other_sales                     text,
    s_oth_sales_tax_inc               text,
    s_internal_sales_amt              text,
    tot_s_return_amt                  text,
    s_return_amt                      text,
    tot_ref_sales                     text,
    s_ifc                             text,
    s_fob_sales_amt                   text,
    tot_sales_deduction               text,
    s_sales_allowance                 text,
    s_rebate                          text,
    s_cash_discount                   text,
    s_price_protection                text,
    s_co_op                           text,
    s_sale_deduction_tax              text,
    tot_net_sales                     text,
    tot_cogs                          text,
    tot_material_cost                 text,
    sc_material_cost                  text,
    sc_matl_cost_loss                 text,
    sc_cctr_matl_cost                 text,
    sc_cctr_matl_loss                 text,
    sc_os_material_cost               text,
    sc_other_matl_cost                text,
    tot_labor_cost                    text,
    sc_labor_cost                     text,
    sc_labor_salaries                 text,
    sc_labor_overtime                 text,
    sc_labor_cost_ps                  text,
    sc_labor_cost_rd                  text,
    tot_depreciation_exp              text,
    sc_depre_exp                      text,
    sc_depre_exp_on_bldg              text,
    sc_depre_exp_on_m_and_e           text,
    tot_mold_exp                      text,
    sc_depre_exp_on_mold              text,
    sc_molds_cost                     text,
    sc_cnc_molds_cost                 text,
    tot_manufac_supp_cost             text,
    sc_mfg_supply_cost                text,
    sc_mfg_repair_and_maint           text,
    sc_manufac_jig_cost               text,
    sc_equip_repair_cost              text,
    sc_supplies_exp                   text,
    tot_expense                       text,
    sc_amort_on_dev_cost              text,
    sc_subcont_cost                   text,
    sc_part_time_svc_exp              text,
    sc_royalty_3rd_party              text,
    sc_royalty_hq                     text,
    sc_utility                        text,
    sc_logistic_cost                  text,
    sc_commission                     text,
    sc_it_cost                        text,
    sc_installation                   text,
    sc_tax_and_dues                   text,
    sc_telecom_exp                    text,
    sc_travel_exp                     text,
    sc_rent_and_lease_exp             text,
    sc_sample_exp                     text,
    sc_packing_exp                    text,
    sc_insurance_premium              text,
    sc_convention_exp                 text,
    sc_svc_exp                        text,
    sc_other_exps                     text,
    sc_consumable_rd                  text,
    sc_ordinary_exp_matl              text,
    sc_outsourcing_svc                text,
    sc_others_rd                      text,
    tot_other_cgs                     text,
    sc_other                          text,
    sc_svc_warranty                   text,
    sc_svc_agent_fee                  text,
    tot_return_cgs                    text,
    sc_return_cgs                     text,
    tot_other_expense                 text,
    tot_other_exp_detail              text,
    sc_lcm                            text,
    sc_e_and_o                        text,
    sc_ramp_up_cost                   text,
    sc_inv_loss_q                     text,
    sc_inv_loss_p                     text,
    sc_subcontractor_adj              text,
    sc_customs_refund                 text,
    sc_matl_price_settle              text,
    sc_vat_china                      text,
    sc_cgs_others                     text,
    tot_logistic_cost_c_type          text,
    sc_transport_inland               text,
    sc_transport_marine               text,
    sc_transport_air                  text,
    sc_transport_other                text,
    sc_insurance_logis                text,
    tot_internal_cgs                  text,
    sc_internal_cgs                   text,
    tot_ref_cogs                      text,
    sc_stat_customs_fee               text,
    sc_stat_incidental                text,
    sc_stat_sub_line_exp              text,
    tot_gross_margin                  text,
    tot_operating_expense             text,
    tot_sales_expense                 text,
    tot_labor_cost_s                  text,
    sa_labor_cost                     text,
    sa_labor_salaries                 text,
    tot_svc_expense                   text,
    sa_svc_warranty                   text,
    sa_svc_qual_support               text,
    sa_svc_agency_fee                 text,
    sa_svc_call_center                text,
    sa_svc_claim                      text,
    sa_svc_freight                    text,
    sa_svc_circulation                text,
    sa_svc_op_support                 text,
    sa_svc_other_exp                  text,
    tot_logistics_cost                text,
    sa_transport_inland               text,
    sa_transport_marine               text,
    sa_transport_air                  text,
    sa_transport_other                text,
    sa_warehouse_fee                  text,
    sa_insurance_logis                text,
    sa_comm                           text,
    tot_marketing_expense             text,
    sa_advertising                    text,
    sa_co_op                          text,
    sa_promotion                      text,
    sa_market_research                text,
    sa_sales_commission               text,
    sa_comm_and_svcchgc_card          text,
    sa_hq_sales_comm                  text,
    sa_corp_promotion                 text,
    tot_royalty                       text,
    sa_royalty_3rd_party              text,
    sa_royalty_hq                     text,
    sa_royalty_lump_sum               text,
    tot_paid_commission               text,
    sa_comm_consult                   text,
    sa_comm_litigation                text,
    sa_comm_audit                     text,
    sa_comm_d_o                       text,
    sa_paid_comm                      text,
    tot_other_expense_s               text,
    sa_depreciation                   text,
    sa_insurance_premium              text,
    sa_sample                         text,
    sa_it_exp                         text,
    sa_lease_and_rent                 text,
    sa_bad_debt_exp                   text,
    sa_travel_exp                     text,
    sa_telecom_exp                    text,
    sa_event_exp                      text,
    sa_survey_exp                     text,
    sa_social_exp                     text,
    sa_convention_exp                 text,
    sa_copyright                      text,
    sa_weee                           text,
    sa_familynet                      text,
    sa_other_exp                      text,
    tot_r_and_d_expense               text,
    tot_internal_expense              text,
    rd_ordinary_exp_matl              text,
    rd_labor                          text,
    rd_depreciation                   text,
    rd_consumable                     text,
    rd_others                         text,
    rd_er                             text,
    rd_mask                           text,
    tot_external_expense              text,
    rd_royalty                        text,
    rd_outsourcing_svc                text,
    tot_g_and_a_expense               text,
    tot_labor_cost_sa                 text,
    ga_labor_cost                     text,
    ga_labor_salaries                 text,
    tot_paid_commission_sa            text,
    ga_comm_consult                   text,
    ga_comm_litigation                text,
    ga_comm_audit                     text,
    ga_comm_d_o                       text,
    ga_comm                           text,
    tot_expense_s                     text,
    ga_depreciation                   text,
    ga_it_exp                         text,
    ga_rent_exp                       text,
    ga_telecom_exp                    text,
    ga_repairs_and_maint_exp          text,
    ga_travel_exp                     text,
    ga_insurance_premium              text,
    ga_convention_exp                 text,
    ga_other                          text,
    tot_operating_profit              text,
    tot_non_op_income_and_expense     text,
    tot_non_op_income                 text,
    op_commission_3rd                 text,
    op_service_claim                  text,
    op_rental_income                  text,
    op_extra_gain                     text,
    op_others                         text,
    tot_non_op_expense                text,
    oe_loss_on_a_r_sale               text,
    oe_extra_loss                     text,
    oe_others                         text,
    tot_gain_loss_on_equity           text,
    tot_gain_on_equity                text,
    eg_gain_on_equity                 text,
    tot_loss_on_equity                text,
    el_loss_on_equity                 text,
    tot_financial_income_and_expense  text,
    tot_finance_profit                text,
    fp_gain_on_fx                     text,
    fp_interest_income                text,
    fp_fin_profit_oths                text,
    tot_finance_loss                  text,
    fe_fo_ex_loss                     text,
    fe_interest_exp_ext               text,
    fe_interest_exp_int               text,
    fe_financial_exp_oth              text,
    tot_profit_before_tax             text,
    tot_corporate_tax                 text,
    corp_tax                          text,
    tot_net_income                    text
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
