-- staging 없이 파일 → pnl_fact 직접 적재.
-- 03_staging.sql 의 to_num()/to_txt() 함수가 먼저 만들어져 있어야 한다
-- (그 파일에서 CREATE FUNCTION 두 개만 실행해도 된다).
--
-- 파일 형식에 맞춰 FIELDS/LINES 두 줄만 고치면 된다.
--   콤마 CSV  : FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"' ESCAPED BY ''
--   탭 TSV    : FIELDS TERMINATED BY '\t' ESCAPED BY ''
--   윈도우 파일: LINES TERMINATED BY '\r\n'   / 그 외: '\n'
--
-- 파일에 테이블로 안 옮길 컬럼이 섞여 있으면, 그 자리 @변수를 SET 절에서 빼기만
-- 하면 된다. @변수는 SET 에서 안 쓰면 그냥 버려진다.
--
-- LOCAL 을 쓰면 자연키 중복이 에러가 아니라 경고(1062)로 처리되고 그 행은
-- 조용히 건너뛴다. 두 번 돌려도 중복이 쌓이진 않지만, 몇 행이 들어갔는지는
-- 아래 SHOW WARNINGS 와 행 수로 직접 확인할 것.

USE sales_pnl;

LOAD DATA LOCAL INFILE 'C:/work/sales_dashboard/salesDTC/rawdata/sales_2526.csv'
    INTO TABLE pnl_fact
    FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"' ESCAPED BY ''
    LINES TERMINATED BY '\r\n'
    IGNORE 1 LINES
(
    @cus_group,
    @record_type,
    @division2,
    @prod_group,
    @fiscal_year,
    @sold_to,
    @forex_rate,
    @sales_usd,
    @op_profit_usd,
    @customer,
    @material_group,
    @nielsen_id,
    @profit_center,
    @sap_division,
    @distribution_channel,
    @period,
    @doc_currency,
    @qty_gross,
    @qty_return,
    @qty_net,
    @tot_s_rrp,
    @reference_price,
    @tot_dealer_discount,
    @s_base_margin,
    @s_contract_margin,
    @s_additional_margin,
    @s_special_margin,
    @tot_s_gross_sales,
    @s_gross_sales_amt,
    @s_other_sales,
    @s_oth_sales_tax_inc,
    @s_internal_sales_amt,
    @tot_s_return_amt,
    @s_return_amt,
    @tot_ref_sales,
    @s_ifc,
    @s_fob_sales_amt,
    @tot_sales_deduction,
    @s_sales_allowance,
    @s_rebate,
    @s_cash_discount,
    @s_price_protection,
    @s_co_op,
    @s_sale_deduction_tax,
    @tot_net_sales,
    @tot_cogs,
    @tot_material_cost,
    @sc_material_cost,
    @sc_matl_cost_loss,
    @sc_cctr_matl_cost,
    @sc_cctr_matl_loss,
    @sc_os_material_cost,
    @sc_other_matl_cost,
    @tot_labor_cost,
    @sc_labor_cost,
    @sc_labor_salaries,
    @sc_labor_overtime,
    @sc_labor_cost_ps,
    @sc_labor_cost_rd,
    @tot_depreciation_exp,
    @sc_depre_exp,
    @sc_depre_exp_on_bldg,
    @sc_depre_exp_on_m_and_e,
    @tot_mold_exp,
    @sc_depre_exp_on_mold,
    @sc_molds_cost,
    @sc_cnc_molds_cost,
    @tot_manufac_supp_cost,
    @sc_mfg_supply_cost,
    @sc_mfg_repair_and_maint,
    @sc_manufac_jig_cost,
    @sc_equip_repair_cost,
    @sc_supplies_exp,
    @tot_expense,
    @sc_amort_on_dev_cost,
    @sc_subcont_cost,
    @sc_part_time_svc_exp,
    @sc_royalty_3rd_party,
    @sc_royalty_hq,
    @sc_utility,
    @sc_logistic_cost,
    @sc_commission,
    @sc_it_cost,
    @sc_installation,
    @sc_tax_and_dues,
    @sc_telecom_exp,
    @sc_travel_exp,
    @sc_rent_and_lease_exp,
    @sc_sample_exp,
    @sc_packing_exp,
    @sc_insurance_premium,
    @sc_convention_exp,
    @sc_svc_exp,
    @sc_other_exps,
    @sc_consumable_rd,
    @sc_ordinary_exp_matl,
    @sc_outsourcing_svc,
    @sc_others_rd,
    @tot_other_cgs,
    @sc_other,
    @sc_svc_warranty,
    @sc_svc_agent_fee,
    @tot_return_cgs,
    @sc_return_cgs,
    @tot_other_expense,
    @tot_other_exp_detail,
    @sc_lcm,
    @sc_e_and_o,
    @sc_ramp_up_cost,
    @sc_inv_loss_q,
    @sc_inv_loss_p,
    @sc_subcontractor_adj,
    @sc_customs_refund,
    @sc_matl_price_settle,
    @sc_vat_china,
    @sc_cgs_others,
    @tot_logistic_cost_c_type,
    @sc_transport_inland,
    @sc_transport_marine,
    @sc_transport_air,
    @sc_transport_other,
    @sc_insurance_logis,
    @tot_internal_cgs,
    @sc_internal_cgs,
    @tot_ref_cogs,
    @sc_stat_customs_fee,
    @sc_stat_incidental,
    @sc_stat_sub_line_exp,
    @tot_gross_margin,
    @tot_operating_expense,
    @tot_sales_expense,
    @tot_labor_cost_s,
    @sa_labor_cost,
    @sa_labor_salaries,
    @tot_svc_expense,
    @sa_svc_warranty,
    @sa_svc_qual_support,
    @sa_svc_agency_fee,
    @sa_svc_call_center,
    @sa_svc_claim,
    @sa_svc_freight,
    @sa_svc_circulation,
    @sa_svc_op_support,
    @sa_svc_other_exp,
    @tot_logistics_cost,
    @sa_transport_inland,
    @sa_transport_marine,
    @sa_transport_air,
    @sa_transport_other,
    @sa_warehouse_fee,
    @sa_insurance_logis,
    @sa_comm,
    @tot_marketing_expense,
    @sa_advertising,
    @sa_co_op,
    @sa_promotion,
    @sa_market_research,
    @sa_sales_commission,
    @sa_comm_and_svcchgc_card,
    @sa_hq_sales_comm,
    @sa_corp_promotion,
    @tot_royalty,
    @sa_royalty_3rd_party,
    @sa_royalty_hq,
    @sa_royalty_lump_sum,
    @tot_paid_commission,
    @sa_comm_consult,
    @sa_comm_litigation,
    @sa_comm_audit,
    @sa_comm_d_o,
    @sa_paid_comm,
    @tot_other_expense_s,
    @sa_depreciation,
    @sa_insurance_premium,
    @sa_sample,
    @sa_it_exp,
    @sa_lease_and_rent,
    @sa_bad_debt_exp,
    @sa_travel_exp,
    @sa_telecom_exp,
    @sa_event_exp,
    @sa_survey_exp,
    @sa_social_exp,
    @sa_convention_exp,
    @sa_copyright,
    @sa_weee,
    @sa_familynet,
    @sa_other_exp,
    @tot_r_and_d_expense,
    @tot_internal_expense,
    @rd_ordinary_exp_matl,
    @rd_labor,
    @rd_depreciation,
    @rd_consumable,
    @rd_others,
    @rd_er,
    @rd_mask,
    @tot_external_expense,
    @rd_royalty,
    @rd_outsourcing_svc,
    @tot_g_and_a_expense,
    @tot_labor_cost_sa,
    @ga_labor_cost,
    @ga_labor_salaries,
    @tot_paid_commission_sa,
    @ga_comm_consult,
    @ga_comm_litigation,
    @ga_comm_audit,
    @ga_comm_d_o,
    @ga_comm,
    @tot_expense_s,
    @ga_depreciation,
    @ga_it_exp,
    @ga_rent_exp,
    @ga_telecom_exp,
    @ga_repairs_and_maint_exp,
    @ga_travel_exp,
    @ga_insurance_premium,
    @ga_convention_exp,
    @ga_other,
    @tot_operating_profit,
    @tot_non_op_income_and_expense,
    @tot_non_op_income,
    @op_commission_3rd,
    @op_service_claim,
    @op_rental_income,
    @op_extra_gain,
    @op_others,
    @tot_non_op_expense,
    @oe_loss_on_a_r_sale,
    @oe_extra_loss,
    @oe_others,
    @tot_gain_loss_on_equity,
    @tot_gain_on_equity,
    @eg_gain_on_equity,
    @tot_loss_on_equity,
    @el_loss_on_equity,
    @tot_financial_income_and_expense,
    @tot_finance_profit,
    @fp_gain_on_fx,
    @fp_interest_income,
    @fp_fin_profit_oths,
    @tot_finance_loss,
    @fe_fo_ex_loss,
    @fe_interest_exp_ext,
    @fe_interest_exp_int,
    @fe_financial_exp_oth,
    @tot_profit_before_tax,
    @tot_corporate_tax,
    @corp_tax,
    @tot_net_income
)
SET
    cus_group = to_txt(@cus_group),
    record_type = to_txt(@record_type),
    division2 = to_txt(@division2),
    prod_group = to_txt(@prod_group),
    fiscal_year = to_num(@fiscal_year),
    sold_to = to_txt(@sold_to),
    forex_rate = to_num(@forex_rate),
    sales_usd = to_num(@sales_usd),
    op_profit_usd = to_num(@op_profit_usd),
    customer = to_txt(@customer),
    material_group = to_txt(@material_group),
    nielsen_id = to_txt(@nielsen_id),
    profit_center = to_txt(@profit_center),
    sap_division = to_txt(@sap_division),
    distribution_channel = to_txt(@distribution_channel),
    period = to_txt(@period),
    doc_currency = to_txt(@doc_currency),
    qty_gross = to_num(@qty_gross),
    qty_return = to_num(@qty_return),
    qty_net = to_num(@qty_net),
    tot_s_rrp = to_num(@tot_s_rrp),
    reference_price = to_num(@reference_price),
    tot_dealer_discount = to_num(@tot_dealer_discount),
    s_base_margin = to_num(@s_base_margin),
    s_contract_margin = to_num(@s_contract_margin),
    s_additional_margin = to_num(@s_additional_margin),
    s_special_margin = to_num(@s_special_margin),
    tot_s_gross_sales = to_num(@tot_s_gross_sales),
    s_gross_sales_amt = to_num(@s_gross_sales_amt),
    s_other_sales = to_num(@s_other_sales),
    s_oth_sales_tax_inc = to_num(@s_oth_sales_tax_inc),
    s_internal_sales_amt = to_num(@s_internal_sales_amt),
    tot_s_return_amt = to_num(@tot_s_return_amt),
    s_return_amt = to_num(@s_return_amt),
    tot_ref_sales = to_num(@tot_ref_sales),
    s_ifc = to_num(@s_ifc),
    s_fob_sales_amt = to_num(@s_fob_sales_amt),
    tot_sales_deduction = to_num(@tot_sales_deduction),
    s_sales_allowance = to_num(@s_sales_allowance),
    s_rebate = to_num(@s_rebate),
    s_cash_discount = to_num(@s_cash_discount),
    s_price_protection = to_num(@s_price_protection),
    s_co_op = to_num(@s_co_op),
    s_sale_deduction_tax = to_num(@s_sale_deduction_tax),
    tot_net_sales = to_num(@tot_net_sales),
    tot_cogs = to_num(@tot_cogs),
    tot_material_cost = to_num(@tot_material_cost),
    sc_material_cost = to_num(@sc_material_cost),
    sc_matl_cost_loss = to_num(@sc_matl_cost_loss),
    sc_cctr_matl_cost = to_num(@sc_cctr_matl_cost),
    sc_cctr_matl_loss = to_num(@sc_cctr_matl_loss),
    sc_os_material_cost = to_num(@sc_os_material_cost),
    sc_other_matl_cost = to_num(@sc_other_matl_cost),
    tot_labor_cost = to_num(@tot_labor_cost),
    sc_labor_cost = to_num(@sc_labor_cost),
    sc_labor_salaries = to_num(@sc_labor_salaries),
    sc_labor_overtime = to_num(@sc_labor_overtime),
    sc_labor_cost_ps = to_num(@sc_labor_cost_ps),
    sc_labor_cost_rd = to_num(@sc_labor_cost_rd),
    tot_depreciation_exp = to_num(@tot_depreciation_exp),
    sc_depre_exp = to_num(@sc_depre_exp),
    sc_depre_exp_on_bldg = to_num(@sc_depre_exp_on_bldg),
    sc_depre_exp_on_m_and_e = to_num(@sc_depre_exp_on_m_and_e),
    tot_mold_exp = to_num(@tot_mold_exp),
    sc_depre_exp_on_mold = to_num(@sc_depre_exp_on_mold),
    sc_molds_cost = to_num(@sc_molds_cost),
    sc_cnc_molds_cost = to_num(@sc_cnc_molds_cost),
    tot_manufac_supp_cost = to_num(@tot_manufac_supp_cost),
    sc_mfg_supply_cost = to_num(@sc_mfg_supply_cost),
    sc_mfg_repair_and_maint = to_num(@sc_mfg_repair_and_maint),
    sc_manufac_jig_cost = to_num(@sc_manufac_jig_cost),
    sc_equip_repair_cost = to_num(@sc_equip_repair_cost),
    sc_supplies_exp = to_num(@sc_supplies_exp),
    tot_expense = to_num(@tot_expense),
    sc_amort_on_dev_cost = to_num(@sc_amort_on_dev_cost),
    sc_subcont_cost = to_num(@sc_subcont_cost),
    sc_part_time_svc_exp = to_num(@sc_part_time_svc_exp),
    sc_royalty_3rd_party = to_num(@sc_royalty_3rd_party),
    sc_royalty_hq = to_num(@sc_royalty_hq),
    sc_utility = to_num(@sc_utility),
    sc_logistic_cost = to_num(@sc_logistic_cost),
    sc_commission = to_num(@sc_commission),
    sc_it_cost = to_num(@sc_it_cost),
    sc_installation = to_num(@sc_installation),
    sc_tax_and_dues = to_num(@sc_tax_and_dues),
    sc_telecom_exp = to_num(@sc_telecom_exp),
    sc_travel_exp = to_num(@sc_travel_exp),
    sc_rent_and_lease_exp = to_num(@sc_rent_and_lease_exp),
    sc_sample_exp = to_num(@sc_sample_exp),
    sc_packing_exp = to_num(@sc_packing_exp),
    sc_insurance_premium = to_num(@sc_insurance_premium),
    sc_convention_exp = to_num(@sc_convention_exp),
    sc_svc_exp = to_num(@sc_svc_exp),
    sc_other_exps = to_num(@sc_other_exps),
    sc_consumable_rd = to_num(@sc_consumable_rd),
    sc_ordinary_exp_matl = to_num(@sc_ordinary_exp_matl),
    sc_outsourcing_svc = to_num(@sc_outsourcing_svc),
    sc_others_rd = to_num(@sc_others_rd),
    tot_other_cgs = to_num(@tot_other_cgs),
    sc_other = to_num(@sc_other),
    sc_svc_warranty = to_num(@sc_svc_warranty),
    sc_svc_agent_fee = to_num(@sc_svc_agent_fee),
    tot_return_cgs = to_num(@tot_return_cgs),
    sc_return_cgs = to_num(@sc_return_cgs),
    tot_other_expense = to_num(@tot_other_expense),
    tot_other_exp_detail = to_num(@tot_other_exp_detail),
    sc_lcm = to_num(@sc_lcm),
    sc_e_and_o = to_num(@sc_e_and_o),
    sc_ramp_up_cost = to_num(@sc_ramp_up_cost),
    sc_inv_loss_q = to_num(@sc_inv_loss_q),
    sc_inv_loss_p = to_num(@sc_inv_loss_p),
    sc_subcontractor_adj = to_num(@sc_subcontractor_adj),
    sc_customs_refund = to_num(@sc_customs_refund),
    sc_matl_price_settle = to_num(@sc_matl_price_settle),
    sc_vat_china = to_num(@sc_vat_china),
    sc_cgs_others = to_num(@sc_cgs_others),
    tot_logistic_cost_c_type = to_num(@tot_logistic_cost_c_type),
    sc_transport_inland = to_num(@sc_transport_inland),
    sc_transport_marine = to_num(@sc_transport_marine),
    sc_transport_air = to_num(@sc_transport_air),
    sc_transport_other = to_num(@sc_transport_other),
    sc_insurance_logis = to_num(@sc_insurance_logis),
    tot_internal_cgs = to_num(@tot_internal_cgs),
    sc_internal_cgs = to_num(@sc_internal_cgs),
    tot_ref_cogs = to_num(@tot_ref_cogs),
    sc_stat_customs_fee = to_num(@sc_stat_customs_fee),
    sc_stat_incidental = to_num(@sc_stat_incidental),
    sc_stat_sub_line_exp = to_num(@sc_stat_sub_line_exp),
    tot_gross_margin = to_num(@tot_gross_margin),
    tot_operating_expense = to_num(@tot_operating_expense),
    tot_sales_expense = to_num(@tot_sales_expense),
    tot_labor_cost_s = to_num(@tot_labor_cost_s),
    sa_labor_cost = to_num(@sa_labor_cost),
    sa_labor_salaries = to_num(@sa_labor_salaries),
    tot_svc_expense = to_num(@tot_svc_expense),
    sa_svc_warranty = to_num(@sa_svc_warranty),
    sa_svc_qual_support = to_num(@sa_svc_qual_support),
    sa_svc_agency_fee = to_num(@sa_svc_agency_fee),
    sa_svc_call_center = to_num(@sa_svc_call_center),
    sa_svc_claim = to_num(@sa_svc_claim),
    sa_svc_freight = to_num(@sa_svc_freight),
    sa_svc_circulation = to_num(@sa_svc_circulation),
    sa_svc_op_support = to_num(@sa_svc_op_support),
    sa_svc_other_exp = to_num(@sa_svc_other_exp),
    tot_logistics_cost = to_num(@tot_logistics_cost),
    sa_transport_inland = to_num(@sa_transport_inland),
    sa_transport_marine = to_num(@sa_transport_marine),
    sa_transport_air = to_num(@sa_transport_air),
    sa_transport_other = to_num(@sa_transport_other),
    sa_warehouse_fee = to_num(@sa_warehouse_fee),
    sa_insurance_logis = to_num(@sa_insurance_logis),
    sa_comm = to_num(@sa_comm),
    tot_marketing_expense = to_num(@tot_marketing_expense),
    sa_advertising = to_num(@sa_advertising),
    sa_co_op = to_num(@sa_co_op),
    sa_promotion = to_num(@sa_promotion),
    sa_market_research = to_num(@sa_market_research),
    sa_sales_commission = to_num(@sa_sales_commission),
    sa_comm_and_svcchgc_card = to_num(@sa_comm_and_svcchgc_card),
    sa_hq_sales_comm = to_num(@sa_hq_sales_comm),
    sa_corp_promotion = to_num(@sa_corp_promotion),
    tot_royalty = to_num(@tot_royalty),
    sa_royalty_3rd_party = to_num(@sa_royalty_3rd_party),
    sa_royalty_hq = to_num(@sa_royalty_hq),
    sa_royalty_lump_sum = to_num(@sa_royalty_lump_sum),
    tot_paid_commission = to_num(@tot_paid_commission),
    sa_comm_consult = to_num(@sa_comm_consult),
    sa_comm_litigation = to_num(@sa_comm_litigation),
    sa_comm_audit = to_num(@sa_comm_audit),
    sa_comm_d_o = to_num(@sa_comm_d_o),
    sa_paid_comm = to_num(@sa_paid_comm),
    tot_other_expense_s = to_num(@tot_other_expense_s),
    sa_depreciation = to_num(@sa_depreciation),
    sa_insurance_premium = to_num(@sa_insurance_premium),
    sa_sample = to_num(@sa_sample),
    sa_it_exp = to_num(@sa_it_exp),
    sa_lease_and_rent = to_num(@sa_lease_and_rent),
    sa_bad_debt_exp = to_num(@sa_bad_debt_exp),
    sa_travel_exp = to_num(@sa_travel_exp),
    sa_telecom_exp = to_num(@sa_telecom_exp),
    sa_event_exp = to_num(@sa_event_exp),
    sa_survey_exp = to_num(@sa_survey_exp),
    sa_social_exp = to_num(@sa_social_exp),
    sa_convention_exp = to_num(@sa_convention_exp),
    sa_copyright = to_num(@sa_copyright),
    sa_weee = to_num(@sa_weee),
    sa_familynet = to_num(@sa_familynet),
    sa_other_exp = to_num(@sa_other_exp),
    tot_r_and_d_expense = to_num(@tot_r_and_d_expense),
    tot_internal_expense = to_num(@tot_internal_expense),
    rd_ordinary_exp_matl = to_num(@rd_ordinary_exp_matl),
    rd_labor = to_num(@rd_labor),
    rd_depreciation = to_num(@rd_depreciation),
    rd_consumable = to_num(@rd_consumable),
    rd_others = to_num(@rd_others),
    rd_er = to_num(@rd_er),
    rd_mask = to_num(@rd_mask),
    tot_external_expense = to_num(@tot_external_expense),
    rd_royalty = to_num(@rd_royalty),
    rd_outsourcing_svc = to_num(@rd_outsourcing_svc),
    tot_g_and_a_expense = to_num(@tot_g_and_a_expense),
    tot_labor_cost_sa = to_num(@tot_labor_cost_sa),
    ga_labor_cost = to_num(@ga_labor_cost),
    ga_labor_salaries = to_num(@ga_labor_salaries),
    tot_paid_commission_sa = to_num(@tot_paid_commission_sa),
    ga_comm_consult = to_num(@ga_comm_consult),
    ga_comm_litigation = to_num(@ga_comm_litigation),
    ga_comm_audit = to_num(@ga_comm_audit),
    ga_comm_d_o = to_num(@ga_comm_d_o),
    ga_comm = to_num(@ga_comm),
    tot_expense_s = to_num(@tot_expense_s),
    ga_depreciation = to_num(@ga_depreciation),
    ga_it_exp = to_num(@ga_it_exp),
    ga_rent_exp = to_num(@ga_rent_exp),
    ga_telecom_exp = to_num(@ga_telecom_exp),
    ga_repairs_and_maint_exp = to_num(@ga_repairs_and_maint_exp),
    ga_travel_exp = to_num(@ga_travel_exp),
    ga_insurance_premium = to_num(@ga_insurance_premium),
    ga_convention_exp = to_num(@ga_convention_exp),
    ga_other = to_num(@ga_other),
    tot_operating_profit = to_num(@tot_operating_profit),
    tot_non_op_income_and_expense = to_num(@tot_non_op_income_and_expense),
    tot_non_op_income = to_num(@tot_non_op_income),
    op_commission_3rd = to_num(@op_commission_3rd),
    op_service_claim = to_num(@op_service_claim),
    op_rental_income = to_num(@op_rental_income),
    op_extra_gain = to_num(@op_extra_gain),
    op_others = to_num(@op_others),
    tot_non_op_expense = to_num(@tot_non_op_expense),
    oe_loss_on_a_r_sale = to_num(@oe_loss_on_a_r_sale),
    oe_extra_loss = to_num(@oe_extra_loss),
    oe_others = to_num(@oe_others),
    tot_gain_loss_on_equity = to_num(@tot_gain_loss_on_equity),
    tot_gain_on_equity = to_num(@tot_gain_on_equity),
    eg_gain_on_equity = to_num(@eg_gain_on_equity),
    tot_loss_on_equity = to_num(@tot_loss_on_equity),
    el_loss_on_equity = to_num(@el_loss_on_equity),
    tot_financial_income_and_expense = to_num(@tot_financial_income_and_expense),
    tot_finance_profit = to_num(@tot_finance_profit),
    fp_gain_on_fx = to_num(@fp_gain_on_fx),
    fp_interest_income = to_num(@fp_interest_income),
    fp_fin_profit_oths = to_num(@fp_fin_profit_oths),
    tot_finance_loss = to_num(@tot_finance_loss),
    fe_fo_ex_loss = to_num(@fe_fo_ex_loss),
    fe_interest_exp_ext = to_num(@fe_interest_exp_ext),
    fe_interest_exp_int = to_num(@fe_interest_exp_int),
    fe_financial_exp_oth = to_num(@fe_financial_exp_oth),
    tot_profit_before_tax = to_num(@tot_profit_before_tax),
    tot_corporate_tax = to_num(@tot_corporate_tax),
    corp_tax = to_num(@corp_tax),
    tot_net_income = to_num(@tot_net_income);

SELECT count(*) AS loaded FROM pnl_fact;
SHOW WARNINGS;

-- 이어서 05_checks.sql 로 검산 (아무 행도 안 나오면 정상).
